<?php
if ( ! defined( 'ABSPATH' ) ) exit;

require_once AK_PATH . 'includes/codes/p2-codes.php';
require_once AK_PATH . 'includes/codes/p2b-codes.php';
require_once AK_PATH . 'includes/codes/p2c-codes.php';
require_once AK_PATH . 'includes/codes/b-codes.php';
require_once AK_PATH . 'includes/codes/c-codes.php';
require_once AK_PATH . 'includes/codes/u-codes.php';

class AK_DB {

    const TABLE   = 'ak_obd_codes';
    const VERSION = '1.1.0';

    /** Eklenti aktive edildiğinde çalışır */
    public static function install() {
        global $wpdb;
        $table   = $wpdb->prefix . self::TABLE;
        $charset = $wpdb->get_charset_collate();

        $sql = "CREATE TABLE IF NOT EXISTS $table (
            id          MEDIUMINT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
            code        VARCHAR(10)  NOT NULL,
            category    CHAR(1)      NOT NULL,
            name_tr     VARCHAR(255) NOT NULL,
            PRIMARY KEY (id),
            UNIQUE KEY code (code),
            KEY category (category)
        ) $charset;";

        require_once ABSPATH . 'wp-admin/includes/upgrade.php';
        dbDelta( $sql );

        if ( get_option( 'ak_db_seeded' ) !== self::VERSION ) {
            self::seed( $table );
            update_option( 'ak_db_seeded', self::VERSION );
        }
    }

    /** Tüm kodları DB'ye yükle */
    private static function seed( $table ) {
        global $wpdb;
        $wpdb->query( "TRUNCATE TABLE $table" );

        $all = self::all_codes();
        $rows = [];
        foreach ( $all as $cat => $codes ) {
            foreach ( $codes as $code => $name ) {
                $rows[] = $wpdb->prepare( '(%s,%s,%s)', $code, $cat, $name );
            }
        }

        // Toplu insert — 500'er chunk
        foreach ( array_chunk( $rows, 500 ) as $chunk ) {
            $wpdb->query(
                "INSERT IGNORE INTO $table (code, category, name_tr) VALUES " . implode( ',', $chunk )
            );
        }
    }

    /** Kategori listesi */
    public static function categories() {
        return [
            'P' => [ 'label' => 'Powertrain (Motor & Şanzıman)', 'icon' => '⚙️', 'color' => '#3b82f6' ],
            'B' => [ 'label' => 'Body (Kaporta & Konfor)',        'icon' => '🚗', 'color' => '#8b5cf6' ],
            'C' => [ 'label' => 'Chassis (Şasi & Fren)',          'icon' => '🛞', 'color' => '#f59e0b' ],
            'U' => [ 'label' => 'Network (Ağ & İletişim)',        'icon' => '📡', 'color' => '#10b981' ],
        ];
    }

    /** Kategorideki kod sayısı */
    public static function count( $category ) {
        global $wpdb;
        $table = $wpdb->prefix . self::TABLE;
        return (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM $table WHERE category=%s", $category ) );
    }

    /** Sayfalı liste */
    public static function get_page( $category, $page = 1, $per_page = 50, $search = '' ) {
        global $wpdb;
        $table  = $wpdb->prefix . self::TABLE;
        $offset = ( $page - 1 ) * $per_page;

        if ( $search ) {
            return $wpdb->get_results( $wpdb->prepare(
                "SELECT code, name_tr FROM $table WHERE category=%s AND (code LIKE %s OR name_tr LIKE %s) ORDER BY code LIMIT %d OFFSET %d",
                $category, "%$search%", "%$search%", $per_page, $offset
            ), ARRAY_A );
        }

        return $wpdb->get_results( $wpdb->prepare(
            "SELECT code, name_tr FROM $table WHERE category=%s ORDER BY code LIMIT %d OFFSET %d",
            $category, $per_page, $offset
        ), ARRAY_A );
    }

    /** Arama (tüm kategoriler) */
    public static function search( $q, $limit = 100 ) {
        global $wpdb;
        $table = $wpdb->prefix . self::TABLE;
        return $wpdb->get_results( $wpdb->prepare(
            "SELECT code, category, name_tr FROM $table WHERE code LIKE %s OR name_tr LIKE %s ORDER BY code LIMIT %d",
            "%$q%", "%$q%", $limit
        ), ARRAY_A );
    }

    /** Tek kod */
    public static function get_code( $code ) {
        global $wpdb;
        $table = $wpdb->prefix . self::TABLE;
        return $wpdb->get_row( $wpdb->prepare(
            "SELECT * FROM $table WHERE code=%s", $code
        ), ARRAY_A );
    }

    /** Kategori için tüm kodlar (blog için) */
    public static function get_all_by_category( $category ) {
        global $wpdb;
        $table = $wpdb->prefix . self::TABLE;
        $rows  = $wpdb->get_results( $wpdb->prepare(
            "SELECT code, name_tr FROM $table WHERE category=%s ORDER BY code",
            $category
        ), ARRAY_A );
        $result = [];
        foreach ( $rows as $r ) $result[ $r['code'] ] = $r['name_tr'];
        return $result;
    }

    /** Tüm standart OBD-II kodları */
    public static function all_codes() {
        return [
            'P' => self::p_codes(),
            'B' => self::b_codes(),
            'C' => self::c_codes(),
            'U' => self::u_codes(),
        ];
    }

    private static function p_codes_1() {
        return [
            // P00xx - Yakıt/Hava Ölçümü
            'P0001'=>'Yakıt Hacim Regülatör Kontrol Devresi Açık',
            'P0002'=>'Yakıt Hacim Regülatör Kontrol Devresi Aralık/Performans',
            'P0003'=>'Yakıt Hacim Regülatör Kontrol Devresi Düşük',
            'P0004'=>'Yakıt Hacim Regülatör Kontrol Devresi Yüksek',
            'P0005'=>'Yakıt Kesme Valfi A Kontrol Devresi Açık',
            'P0006'=>'Yakıt Kesme Valfi A Kontrol Devresi Düşük',
            'P0007'=>'Yakıt Kesme Valfi A Kontrol Devresi Yüksek',
            'P0008'=>'Motor Konum Sistemi Performans Banka 1',
            'P0009'=>'Motor Konum Sistemi Performans Banka 2',
            'P0010'=>'Emme Eksantrik Mili Aktüatör Devre Arızası Banka 1',
            'P0011'=>'Emme Eksantrik Mili Zamanlama Aşırı İleri Banka 1',
            'P0012'=>'Emme Eksantrik Mili Zamanlama Aşırı Geri Banka 1',
            'P0013'=>'Egzoz Eksantrik Mili Aktüatör Devre Arızası Banka 1',
            'P0014'=>'Egzoz Eksantrik Mili Zamanlama Aşırı İleri Banka 1',
            'P0015'=>'Egzoz Eksantrik Mili Zamanlama Aşırı Geri Banka 1',
            'P0016'=>'Krank/Eksantrik Mili Korelasyonu Banka 1 Sensör A',
            'P0017'=>'Krank/Eksantrik Mili Korelasyonu Banka 1 Sensör B',
            'P0018'=>'Krank/Eksantrik Mili Korelasyonu Banka 2 Sensör A',
            'P0019'=>'Krank/Eksantrik Mili Korelasyonu Banka 2 Sensör B',
            'P0020'=>'Emme Eksantrik Mili Aktüatör Devre Arızası Banka 2',
            'P0021'=>'Emme Eksantrik Mili Zamanlama Aşırı İleri Banka 2',
            'P0022'=>'Emme Eksantrik Mili Zamanlama Aşırı Geri Banka 2',
            'P0023'=>'Egzoz Eksantrik Mili Aktüatör Devre Arızası Banka 2',
            'P0024'=>'Egzoz Eksantrik Mili Zamanlama Aşırı İleri Banka 2',
            'P0025'=>'Egzoz Eksantrik Mili Zamanlama Aşırı Geri Banka 2',
            'P0026'=>'Emme Valfi Kontrol Solenoid Aralık/Performans Banka 1',
            'P0027'=>'Egzoz Valfi Kontrol Solenoid Aralık/Performans Banka 1',
            'P0028'=>'Emme Valfi Kontrol Solenoid Aralık/Performans Banka 2',
            'P0029'=>'Egzoz Valfi Kontrol Solenoid Aralık/Performans Banka 2',
            'P0030'=>'HO2S Isıtıcı Kontrol Devresi Banka 1 Sensör 1',
            'P0031'=>'HO2S Isıtıcı Kontrol Devresi Düşük Banka 1 Sensör 1',
            'P0032'=>'HO2S Isıtıcı Kontrol Devresi Yüksek Banka 1 Sensör 1',
            'P0033'=>'Turbo Şarj Bypass Valfi Kontrol Devresi',
            'P0034'=>'Turbo Şarj Bypass Valfi Kontrol Devresi Düşük',
            'P0035'=>'Turbo Şarj Bypass Valfi Kontrol Devresi Yüksek',
            'P0036'=>'HO2S Isıtıcı Kontrol Devresi Banka 1 Sensör 2',
            'P0037'=>'HO2S Isıtıcı Kontrol Devresi Düşük Banka 1 Sensör 2',
            'P0038'=>'HO2S Isıtıcı Kontrol Devresi Yüksek Banka 1 Sensör 2',
            'P0039'=>'Turbo/Süper Şarj Bypass Valfi Aralık/Performans',
            'P0040'=>'O2 Sensörü Sinyalleri Yer Değiştirmiş B1S1/B2S1',
            'P0041'=>'O2 Sensörü Sinyalleri Yer Değiştirmiş B1S2/B2S2',
            'P0042'=>'HO2S Isıtıcı Kontrol Devresi Banka 1 Sensör 3',
            'P0043'=>'HO2S Isıtıcı Kontrol Devresi Düşük Banka 1 Sensör 3',
            'P0044'=>'HO2S Isıtıcı Kontrol Devresi Yüksek Banka 1 Sensör 3',
            'P0045'=>'Turbo/Süper Şarj Boost Kontrol Solenoid Açık',
            'P0046'=>'Turbo/Süper Şarj Boost Kontrol Solenoid Aralık/Performans',
            'P0047'=>'Turbo/Süper Şarj Boost Kontrol Solenoid Düşük',
            'P0048'=>'Turbo/Süper Şarj Boost Kontrol Solenoid Yüksek',
            'P0049'=>'Turbo/Süper Şarj Türbin Aşırı Hız',
            'P0050'=>'HO2S Isıtıcı Kontrol Devresi Banka 2 Sensör 1',
            'P0051'=>'HO2S Isıtıcı Kontrol Devresi Düşük Banka 2 Sensör 1',
            'P0052'=>'HO2S Isıtıcı Kontrol Devresi Yüksek Banka 2 Sensör 1',
            'P0053'=>'HO2S Isıtıcı Direnci Banka 1 Sensör 1',
            'P0054'=>'HO2S Isıtıcı Direnci Banka 1 Sensör 2',
            'P0055'=>'HO2S Isıtıcı Direnci Banka 1 Sensör 3',
            'P0056'=>'HO2S Isıtıcı Kontrol Devresi Banka 2 Sensör 2',
            'P0057'=>'HO2S Isıtıcı Kontrol Devresi Düşük Banka 2 Sensör 2',
            'P0058'=>'HO2S Isıtıcı Kontrol Devresi Yüksek Banka 2 Sensör 2',
            'P0059'=>'HO2S Isıtıcı Direnci Banka 2 Sensör 1',
            'P0060'=>'HO2S Isıtıcı Direnci Banka 2 Sensör 2',
            'P0061'=>'HO2S Isıtıcı Direnci Banka 2 Sensör 3',
            'P0062'=>'HO2S Isıtıcı Kontrol Devresi Banka 2 Sensör 3',
            'P0063'=>'HO2S Isıtıcı Kontrol Devresi Düşük Banka 2 Sensör 3',
            'P0064'=>'HO2S Isıtıcı Kontrol Devresi Yüksek Banka 2 Sensör 3',
            'P0065'=>'Hava Yardımlı Enjektör Kontrol Aralık/Performans',
            'P0066'=>'Hava Yardımlı Enjektör Kontrol Devresi Düşük',
            'P0067'=>'Hava Yardımlı Enjektör Kontrol Devresi Yüksek',
            'P0068'=>'MAP/MAF - Gaz Kelebeği Konum Korelasyonu',
            'P0069'=>'Manifold Mutlak Basınç - Barometrik Basınç Korelasyonu',
            'P0070'=>'Dış Hava Sıcaklık Sensörü Devre Arızası',
            'P0071'=>'Dış Hava Sıcaklık Sensörü Aralık/Performans',
            'P0072'=>'Dış Hava Sıcaklık Sensörü Düşük Giriş',
            'P0073'=>'Dış Hava Sıcaklık Sensörü Yüksek Giriş',
            'P0074'=>'Dış Hava Sıcaklık Sensörü Aralıklı',
            'P0075'=>'Emme Valfi Kontrol Solenoid Devresi Banka 1',
            'P0076'=>'Emme Valfi Kontrol Solenoid Devresi Düşük Banka 1',
            'P0077'=>'Emme Valfi Kontrol Solenoid Devresi Yüksek Banka 1',
            'P0078'=>'Egzoz Valfi Kontrol Solenoid Devresi Banka 1',
            'P0079'=>'Egzoz Valfi Kontrol Solenoid Devresi Düşük Banka 1',
            'P0080'=>'Egzoz Valfi Kontrol Solenoid Devresi Yüksek Banka 1',
            'P0081'=>'Emme Valfi Kontrol Solenoid Devresi Banka 2',
            'P0082'=>'Emme Valfi Kontrol Solenoid Devresi Düşük Banka 2',
            'P0083'=>'Emme Valfi Kontrol Solenoid Devresi Yüksek Banka 2',
            'P0084'=>'Egzoz Valfi Kontrol Solenoid Devresi Banka 2',
            'P0085'=>'Egzoz Valfi Kontrol Solenoid Devresi Düşük Banka 2',
            'P0086'=>'Egzoz Valfi Kontrol Solenoid Devresi Yüksek Banka 2',
            'P0087'=>'Yakıt Ray/Sistem Basıncı Çok Düşük',
            'P0088'=>'Yakıt Ray/Sistem Basıncı Çok Yüksek',
            'P0089'=>'Yakıt Basınç Regülatörü Performans',
            'P0090'=>'Yakıt Basınç Regülatörü 1 Kontrol Devresi',
            'P0091'=>'Yakıt Basınç Regülatörü 1 Kontrol Devresi Düşük',
            'P0092'=>'Yakıt Basınç Regülatörü 1 Kontrol Devresi Yüksek',
            'P0093'=>'Yakıt Sistemi Büyük Kaçak',
            'P0094'=>'Yakıt Sistemi Küçük Kaçak',
            'P0095'=>'Emme Havası Sıcaklık Sensörü 2 Devre Arızası',
            'P0096'=>'Emme Havası Sıcaklık Sensörü 2 Aralık/Performans',
            'P0097'=>'Emme Havası Sıcaklık Sensörü 2 Düşük Giriş',
            'P0098'=>'Emme Havası Sıcaklık Sensörü 2 Yüksek Giriş',
            'P0099'=>'Emme Havası Sıcaklık Sensörü 2 Aralıklı/Hatalı',
            // P01xx - Hava/Yakıt Ölçümü
            'P0100'=>'Hava Kütlesi Akış Sensörü Devre Arızası',
            'P0101'=>'Hava Kütlesi Akış Sensörü Aralık/Performans',
            'P0102'=>'Hava Kütlesi Akış Sensörü Düşük Giriş',
            'P0103'=>'Hava Kütlesi Akış Sensörü Yüksek Giriş',
            'P0104'=>'Hava Kütlesi Akış Sensörü Aralıklı',
            'P0105'=>'Manifold Mutlak Basınç/Barometrik Basınç Devre Arızası',
            'P0106'=>'Manifold Mutlak Basınç/Barometrik Basınç Aralık/Performans',
            'P0107'=>'Manifold Mutlak Basınç/Barometrik Basınç Düşük Giriş',
            'P0108'=>'Manifold Mutlak Basınç/Barometrik Basınç Yüksek Giriş',
            'P0109'=>'Manifold Mutlak Basınç/Barometrik Basınç Aralıklı',
            'P0110'=>'Emme Havası Sıcaklık Sensörü Devre Arızası',
            'P0111'=>'Emme Havası Sıcaklık Sensörü Aralık/Performans',
            'P0112'=>'Emme Havası Sıcaklık Sensörü Düşük Giriş',
            'P0113'=>'Emme Havası Sıcaklık Sensörü Yüksek Giriş',
            'P0114'=>'Emme Havası Sıcaklık Sensörü Aralıklı',
            'P0115'=>'Motor Soğutma Suyu Sıcaklık Sensörü Devre Arızası',
            'P0116'=>'Motor Soğutma Suyu Sıcaklık Sensörü Aralık/Performans',
            'P0117'=>'Motor Soğutma Suyu Sıcaklık Sensörü Düşük Giriş',
            'P0118'=>'Motor Soğutma Suyu Sıcaklık Sensörü Yüksek Giriş',
            'P0119'=>'Motor Soğutma Suyu Sıcaklık Sensörü Aralıklı',
            'P0120'=>'Gaz Kelebeği/Pedal Konum Sensörü A Devre Arızası',
            'P0121'=>'Gaz Kelebeği/Pedal Konum Sensörü A Aralık/Performans',
            'P0122'=>'Gaz Kelebeği/Pedal Konum Sensörü A Düşük Giriş',
            'P0123'=>'Gaz Kelebeği/Pedal Konum Sensörü A Yüksek Giriş',
            'P0124'=>'Gaz Kelebeği/Pedal Konum Sensörü A Aralıklı',
            'P0125'=>'Kapalı Döngü Yakıt Kontrolü için Yetersiz Soğutma Suyu Sıcaklığı',
            'P0126'=>'Kararlı Çalışma için Yetersiz Soğutma Suyu Sıcaklığı',
            'P0127'=>'Emme Havası Sıcaklığı Çok Yüksek',
            'P0128'=>'Soğutma Suyu Termostatı Soğutma Suyu Sıcaklığı Modelden Düşük',
            'P0129'=>'Barometrik Basınç Çok Düşük',
            'P0130'=>'O2 Sensörü Devre Arızası Banka 1 Sensör 1',
            'P0131'=>'O2 Sensörü Düşük Voltaj Banka 1 Sensör 1',
            'P0132'=>'O2 Sensörü Yüksek Voltaj Banka 1 Sensör 1',
            'P0133'=>'O2 Sensörü Yavaş Tepki Banka 1 Sensör 1',
            'P0134'=>'O2 Sensörü Aktivite Yok Banka 1 Sensör 1',
            'P0135'=>'O2 Sensörü Isıtıcı Devre Arızası Banka 1 Sensör 1',
            'P0136'=>'O2 Sensörü Devre Arızası Banka 1 Sensör 2',
            'P0137'=>'O2 Sensörü Düşük Voltaj Banka 1 Sensör 2',
            'P0138'=>'O2 Sensörü Yüksek Voltaj Banka 1 Sensör 2',
            'P0139'=>'O2 Sensörü Yavaş Tepki Banka 1 Sensör 2',
            'P0140'=>'O2 Sensörü Aktivite Yok Banka 1 Sensör 2',
            'P0141'=>'O2 Sensörü Isıtıcı Devre Arızası Banka 1 Sensör 2',
            'P0142'=>'O2 Sensörü Devre Arızası Banka 1 Sensör 3',
            'P0143'=>'O2 Sensörü Düşük Voltaj Banka 1 Sensör 3',
            'P0144'=>'O2 Sensörü Yüksek Voltaj Banka 1 Sensör 3',
            'P0145'=>'O2 Sensörü Yavaş Tepki Banka 1 Sensör 3',
            'P0146'=>'O2 Sensörü Aktivite Yok Banka 1 Sensör 3',
            'P0147'=>'O2 Sensörü Isıtıcı Devre Arızası Banka 1 Sensör 3',
            'P0148'=>'Yakıt Teslimat Hatası',
            'P0149'=>'Yakıt Zamanlama Hatası',
            'P0150'=>'O2 Sensörü Devre Arızası Banka 2 Sensör 1',
            'P0151'=>'O2 Sensörü Düşük Voltaj Banka 2 Sensör 1',
            'P0152'=>'O2 Sensörü Yüksek Voltaj Banka 2 Sensör 1',
            'P0153'=>'O2 Sensörü Yavaş Tepki Banka 2 Sensör 1',
            'P0154'=>'O2 Sensörü Aktivite Yok Banka 2 Sensör 1',
            'P0155'=>'O2 Sensörü Isıtıcı Devre Arızası Banka 2 Sensör 1',
            'P0156'=>'O2 Sensörü Devre Arızası Banka 2 Sensör 2',
            'P0157'=>'O2 Sensörü Düşük Voltaj Banka 2 Sensör 2',
            'P0158'=>'O2 Sensörü Yüksek Voltaj Banka 2 Sensör 2',
            'P0159'=>'O2 Sensörü Yavaş Tepki Banka 2 Sensör 2',
            'P0160'=>'O2 Sensörü Aktivite Yok Banka 2 Sensör 2',
            'P0161'=>'O2 Sensörü Isıtıcı Devre Arızası Banka 2 Sensör 2',
            'P0162'=>'O2 Sensörü Devre Arızası Banka 2 Sensör 3',
            'P0163'=>'O2 Sensörü Düşük Voltaj Banka 2 Sensör 3',
            'P0164'=>'O2 Sensörü Yüksek Voltaj Banka 2 Sensör 3',
            'P0165'=>'O2 Sensörü Yavaş Tepki Banka 2 Sensör 3',
            'P0166'=>'O2 Sensörü Aktivite Yok Banka 2 Sensör 3',
            'P0167'=>'O2 Sensörü Isıtıcı Devre Arızası Banka 2 Sensör 3',
            'P0168'=>'Yakıt Sıcaklığı Çok Yüksek',
            'P0169'=>'Yanlış Yakıt Bileşimi',
            'P0170'=>'Yakıt Trim Arızası Banka 1',
            'P0171'=>'Sistem Çok Fakir Banka 1',
            'P0172'=>'Sistem Çok Zengin Banka 1',
            'P0173'=>'Yakıt Trim Arızası Banka 2',
            'P0174'=>'Sistem Çok Fakir Banka 2',
            'P0175'=>'Sistem Çok Zengin Banka 2',
            'P0176'=>'Yakıt Bileşimi Sensörü Devre Arızası',
            'P0177'=>'Yakıt Bileşimi Sensörü Aralık/Performans',
            'P0178'=>'Yakıt Bileşimi Sensörü Düşük Giriş',
            'P0179'=>'Yakıt Bileşimi Sensörü Yüksek Giriş',
            'P0180'=>'Yakıt Sıcaklık Sensörü A Devre Arızası',
            'P0181'=>'Yakıt Sıcaklık Sensörü A Aralık/Performans',
            'P0182'=>'Yakıt Sıcaklık Sensörü A Düşük Giriş',
            'P0183'=>'Yakıt Sıcaklık Sensörü A Yüksek Giriş',
            'P0184'=>'Yakıt Sıcaklık Sensörü A Aralıklı',
            'P0185'=>'Yakıt Sıcaklık Sensörü B Devre Arızası',
            'P0186'=>'Yakıt Sıcaklık Sensörü B Aralık/Performans',
            'P0187'=>'Yakıt Sıcaklık Sensörü B Düşük Giriş',
            'P0188'=>'Yakıt Sıcaklık Sensörü B Yüksek Giriş',
            'P0189'=>'Yakıt Sıcaklık Sensörü B Aralıklı',
            'P0190'=>'Yakıt Ray Basınç Sensörü Devre Arızası',
            'P0191'=>'Yakıt Ray Basınç Sensörü Aralık/Performans',
            'P0192'=>'Yakıt Ray Basınç Sensörü Düşük Giriş',
            'P0193'=>'Yakıt Ray Basınç Sensörü Yüksek Giriş',
            'P0194'=>'Yakıt Ray Basınç Sensörü Aralıklı',
            'P0195'=>'Motor Yağ Sıcaklık Sensörü Arızası',
            'P0196'=>'Motor Yağ Sıcaklık Sensörü Aralık/Performans',
            'P0197'=>'Motor Yağ Sıcaklık Sensörü Düşük',
            'P0198'=>'Motor Yağ Sıcaklık Sensörü Yüksek',
            'P0199'=>'Motor Yağ Sıcaklık Sensörü Aralıklı',
        ];
    }

    private static function p_codes_2() {
        return [
            // P02xx - Enjektör
            'P0200'=>'Enjektör Devre Arızası',
            'P0201'=>'1. Silindir Enjektör Devre Arızası',
            'P0202'=>'2. Silindir Enjektör Devre Arızası',
            'P0203'=>'3. Silindir Enjektör Devre Arızası',
            'P0204'=>'4. Silindir Enjektör Devre Arızası',
            'P0205'=>'5. Silindir Enjektör Devre Arızası',
            'P0206'=>'6. Silindir Enjektör Devre Arızası',
            'P0207'=>'7. Silindir Enjektör Devre Arızası',
            'P0208'=>'8. Silindir Enjektör Devre Arızası',
            'P0209'=>'9. Silindir Enjektör Devre Arızası',
            'P0210'=>'10. Silindir Enjektör Devre Arızası',
            'P0211'=>'11. Silindir Enjektör Devre Arızası',
            'P0212'=>'12. Silindir Enjektör Devre Arızası',
            'P0213'=>'Soğuk Start Enjektörü 1 Arızası',
            'P0214'=>'Soğuk Start Enjektörü 2 Arızası',
            'P0215'=>'Motor Kapatma Solenoid Arızası',
            'P0216'=>'Enjektör/Ateşleme Zamanlama Kontrol Devre Arızası',
            'P0217'=>'Motor Aşırı Isınma Durumu',
            'P0218'=>'Şanzıman Aşırı Isınma Durumu',
            'P0219'=>'Motor Aşırı Hız Durumu',
            'P0220'=>'Gaz Kelebeği/Pedal Konum Sensörü B Devre Arızası',
            'P0221'=>'Gaz Kelebeği/Pedal Konum Sensörü B Aralık/Performans',
            'P0222'=>'Gaz Kelebeği/Pedal Konum Sensörü B Düşük Giriş',
            'P0223'=>'Gaz Kelebeği/Pedal Konum Sensörü B Yüksek Giriş',
            'P0224'=>'Gaz Kelebeği/Pedal Konum Sensörü B Aralıklı',
            'P0225'=>'Gaz Kelebeği/Pedal Konum Sensörü C Devre Arızası',
            'P0226'=>'Gaz Kelebeği/Pedal Konum Sensörü C Aralık/Performans',
            'P0227'=>'Gaz Kelebeği/Pedal Konum Sensörü C Düşük Giriş',
            'P0228'=>'Gaz Kelebeği/Pedal Konum Sensörü C Yüksek Giriş',
            'P0229'=>'Gaz Kelebeği/Pedal Konum Sensörü C Aralıklı',
            'P0230'=>'Yakıt Pompası Birincil Devre Arızası',
            'P0231'=>'Yakıt Pompası İkincil Devre Düşük Voltaj',
            'P0232'=>'Yakıt Pompası İkincil Devre Yüksek Voltaj',
            'P0233'=>'Yakıt Pompası İkincil Devre Aralıklı',
            'P0234'=>'Turbo/Süper Şarj Aşırı Boost Durumu',
            'P0235'=>'Turbo Şarj Boost Sensörü A Devre Arızası',
            'P0236'=>'Turbo Şarj Boost Sensörü A Aralık/Performans',
            'P0237'=>'Turbo Şarj Boost Sensörü A Düşük',
            'P0238'=>'Turbo Şarj Boost Sensörü A Yüksek',
            'P0239'=>'Turbo Şarj Boost Sensörü B Devre Arızası',
            'P0240'=>'Turbo Şarj Boost Sensörü B Aralık/Performans',
            'P0241'=>'Turbo Şarj Boost Sensörü B Düşük',
            'P0242'=>'Turbo Şarj Boost Sensörü B Yüksek',
            'P0243'=>'Turbo Şarj Wastegate Solenoid A Arızası',
            'P0244'=>'Turbo Şarj Wastegate Solenoid A Aralık/Performans',
            'P0245'=>'Turbo Şarj Wastegate Solenoid A Düşük',
            'P0246'=>'Turbo Şarj Wastegate Solenoid A Yüksek',
            'P0247'=>'Turbo Şarj Wastegate Solenoid B Arızası',
            'P0248'=>'Turbo Şarj Wastegate Solenoid B Aralık/Performans',
            'P0249'=>'Turbo Şarj Wastegate Solenoid B Düşük',
            'P0250'=>'Turbo Şarj Wastegate Solenoid B Yüksek',
            'P0261'=>'1. Silindir Enjektör Devre Düşük',
            'P0262'=>'1. Silindir Enjektör Devre Yüksek',
            'P0263'=>'1. Silindir Katkı Dengesi Arızası',
            'P0264'=>'2. Silindir Enjektör Devre Düşük',
            'P0265'=>'2. Silindir Enjektör Devre Yüksek',
            'P0266'=>'2. Silindir Katkı Dengesi Arızası',
            'P0267'=>'3. Silindir Enjektör Devre Düşük',
            'P0268'=>'3. Silindir Enjektör Devre Yüksek',
            'P0269'=>'3. Silindir Katkı Dengesi Arızası',
            'P0270'=>'4. Silindir Enjektör Devre Düşük',
            'P0271'=>'4. Silindir Enjektör Devre Yüksek',
            'P0272'=>'4. Silindir Katkı Dengesi Arızası',
            'P0273'=>'5. Silindir Enjektör Devre Düşük',
            'P0274'=>'5. Silindir Enjektör Devre Yüksek',
            'P0275'=>'5. Silindir Katkı Dengesi Arızası',
            'P0276'=>'6. Silindir Enjektör Devre Düşük',
            'P0277'=>'6. Silindir Enjektör Devre Yüksek',
            'P0278'=>'6. Silindir Katkı Dengesi Arızası',
            'P0279'=>'7. Silindir Enjektör Devre Düşük',
            'P0280'=>'7. Silindir Enjektör Devre Yüksek',
            'P0281'=>'7. Silindir Katkı Dengesi Arızası',
            'P0282'=>'8. Silindir Enjektör Devre Düşük',
            'P0283'=>'8. Silindir Enjektör Devre Yüksek',
            'P0284'=>'8. Silindir Katkı Dengesi Arızası',
            'P0297'=>'Araç Aşırı Hız Durumu',
            'P0298'=>'Motor Yağ Aşırı Sıcaklık',
            'P0299'=>'Turbo/Süper Şarj Düşük Boost',
            // P03xx - Ateşleme
            'P0300'=>'Rastgele/Çoklu Silindir Ateşleme Kaçağı',
            'P0301'=>'1. Silindir Ateşleme Kaçağı',
            'P0302'=>'2. Silindir Ateşleme Kaçağı',
            'P0303'=>'3. Silindir Ateşleme Kaçağı',
            'P0304'=>'4. Silindir Ateşleme Kaçağı',
            'P0305'=>'5. Silindir Ateşleme Kaçağı',
            'P0306'=>'6. Silindir Ateşleme Kaçağı',
            'P0307'=>'7. Silindir Ateşleme Kaçağı',
            'P0308'=>'8. Silindir Ateşleme Kaçağı',
            'P0309'=>'9. Silindir Ateşleme Kaçağı',
            'P0310'=>'10. Silindir Ateşleme Kaçağı',
            'P0311'=>'11. Silindir Ateşleme Kaçağı',
            'P0312'=>'12. Silindir Ateşleme Kaçağı',
            'P0313'=>'Düşük Yakıt ile Ateşleme Kaçağı',
            'P0314'=>'Tek Silindir Ateşleme Kaçağı Silindir Belirtilmemiş',
            'P0315'=>'Krank Mili Konum Sistemi Varyasyon Öğrenilmemiş',
            'P0316'=>'Start Sırasında Ateşleme Kaçağı İlk 1000 Devir',
            'P0320'=>'Ateşleme/Dağıtıcı Motor Hız Giriş Devresi Arızası',
            'P0321'=>'Ateşleme/Dağıtıcı Motor Hız Giriş Devresi Aralık/Performans',
            'P0322'=>'Ateşleme/Dağıtıcı Motor Hız Giriş Devresi Sinyal Yok',
            'P0323'=>'Ateşleme/Dağıtıcı Motor Hız Giriş Devresi Aralıklı',
            'P0324'=>'Vuruntu Kontrol Sistemi Hatası',
            'P0325'=>'Vuruntu Sensörü 1 Devre Arızası Banka 1',
            'P0326'=>'Vuruntu Sensörü 1 Aralık/Performans Banka 1',
            'P0327'=>'Vuruntu Sensörü 1 Düşük Giriş Banka 1',
            'P0328'=>'Vuruntu Sensörü 1 Yüksek Giriş Banka 1',
            'P0329'=>'Vuruntu Sensörü 1 Aralıklı Banka 1',
            'P0330'=>'Vuruntu Sensörü 2 Devre Arızası Banka 2',
            'P0331'=>'Vuruntu Sensörü 2 Aralık/Performans Banka 2',
            'P0332'=>'Vuruntu Sensörü 2 Düşük Giriş Banka 2',
            'P0333'=>'Vuruntu Sensörü 2 Yüksek Giriş Banka 2',
            'P0334'=>'Vuruntu Sensörü 2 Aralıklı Banka 2',
            'P0335'=>'Krank Mili Konum Sensörü A Devre Arızası',
            'P0336'=>'Krank Mili Konum Sensörü A Aralık/Performans',
            'P0337'=>'Krank Mili Konum Sensörü A Düşük Giriş',
            'P0338'=>'Krank Mili Konum Sensörü A Yüksek Giriş',
            'P0339'=>'Krank Mili Konum Sensörü A Aralıklı',
            'P0340'=>'Eksantrik Mili Konum Sensörü A Devre Arızası Banka 1',
            'P0341'=>'Eksantrik Mili Konum Sensörü A Aralık/Performans Banka 1',
            'P0342'=>'Eksantrik Mili Konum Sensörü A Düşük Giriş Banka 1',
            'P0343'=>'Eksantrik Mili Konum Sensörü A Yüksek Giriş Banka 1',
            'P0344'=>'Eksantrik Mili Konum Sensörü A Aralıklı Banka 1',
            'P0345'=>'Eksantrik Mili Konum Sensörü A Devre Arızası Banka 2',
            'P0346'=>'Eksantrik Mili Konum Sensörü A Aralık/Performans Banka 2',
            'P0347'=>'Eksantrik Mili Konum Sensörü A Düşük Giriş Banka 2',
            'P0348'=>'Eksantrik Mili Konum Sensörü A Yüksek Giriş Banka 2',
            'P0349'=>'Eksantrik Mili Konum Sensörü A Aralıklı Banka 2',
            'P0350'=>'Ateşleme Bobini Birincil/İkincil Devre Arızası',
            'P0351'=>'1. Silindir Ateşleme Bobini Devre Arızası',
            'P0352'=>'2. Silindir Ateşleme Bobini Devre Arızası',
            'P0353'=>'3. Silindir Ateşleme Bobini Devre Arızası',
            'P0354'=>'4. Silindir Ateşleme Bobini Devre Arızası',
            'P0355'=>'5. Silindir Ateşleme Bobini Devre Arızası',
            'P0356'=>'6. Silindir Ateşleme Bobini Devre Arızası',
            'P0357'=>'7. Silindir Ateşleme Bobini Devre Arızası',
            'P0358'=>'8. Silindir Ateşleme Bobini Devre Arızası',
            'P0359'=>'9. Silindir Ateşleme Bobini Devre Arızası',
            'P0360'=>'10. Silindir Ateşleme Bobini Devre Arızası',
            'P0361'=>'11. Silindir Ateşleme Bobini Devre Arızası',
            'P0362'=>'12. Silindir Ateşleme Bobini Devre Arızası',
            'P0363'=>'Ateşleme Kaçağı Yakıt Kesildi',
            'P0380'=>'Glow Plug/Isıtıcı Devre A Arızası',
            'P0381'=>'Glow Plug/Isıtıcı Gösterge Devre Arızası',
            'P0382'=>'Glow Plug/Isıtıcı Devre B Arızası',
            'P0385'=>'Krank Mili Konum Sensörü B Devre Arızası',
            'P0386'=>'Krank Mili Konum Sensörü B Aralık/Performans',
            'P0387'=>'Krank Mili Konum Sensörü B Düşük Giriş',
            'P0388'=>'Krank Mili Konum Sensörü B Yüksek Giriş',
            'P0389'=>'Krank Mili Konum Sensörü B Aralıklı',
            'P0390'=>'Eksantrik Mili Konum Sensörü B Devre Arızası Banka 2',
            'P0391'=>'Eksantrik Mili Konum Sensörü B Aralık/Performans Banka 2',
            'P0392'=>'Eksantrik Mili Konum Sensörü B Düşük Giriş Banka 2',
            'P0393'=>'Eksantrik Mili Konum Sensörü B Yüksek Giriş Banka 2',
            'P0394'=>'Eksantrik Mili Konum Sensörü B Aralıklı Banka 2',
        ];
    }

    private static function p_codes_3() {
        return [
            // P04xx - Emisyon
            'P0400'=>'EGR Akış Arızası',
            'P0401'=>'EGR Akışı Yetersiz',
            'P0402'=>'EGR Akışı Aşırı',
            'P0403'=>'EGR Kontrol Devresi Arızası',
            'P0404'=>'EGR Kontrol Devresi Aralık/Performans',
            'P0405'=>'EGR Sensörü A Devre Düşük',
            'P0406'=>'EGR Sensörü A Devre Yüksek',
            'P0407'=>'EGR Sensörü B Devre Düşük',
            'P0408'=>'EGR Sensörü B Devre Yüksek',
            'P0409'=>'EGR Sensörü A Devre Arızası',
            'P0410'=>'İkincil Hava Enjeksiyon Sistemi Arızası',
            'P0411'=>'İkincil Hava Enjeksiyon Sistemi Yanlış Akış',
            'P0412'=>'İkincil Hava Enjeksiyon Sistemi Anahtarlama Valfi A Devre Arızası',
            'P0413'=>'İkincil Hava Enjeksiyon Sistemi Anahtarlama Valfi A Devre Açık',
            'P0414'=>'İkincil Hava Enjeksiyon Sistemi Anahtarlama Valfi A Devre Kısa',
            'P0415'=>'İkincil Hava Enjeksiyon Sistemi Anahtarlama Valfi B Devre Arızası',
            'P0416'=>'İkincil Hava Enjeksiyon Sistemi Anahtarlama Valfi B Devre Açık',
            'P0417'=>'İkincil Hava Enjeksiyon Sistemi Anahtarlama Valfi B Devre Kısa',
            'P0418'=>'İkincil Hava Enjeksiyon Sistemi Röle A Devre Arızası',
            'P0419'=>'İkincil Hava Enjeksiyon Sistemi Röle B Devre Arızası',
            'P0420'=>'Katalitik Konvertör Sistem Verimliliği Düşük Banka 1',
            'P0421'=>'Isınma Katalitik Konvertör Verimliliği Düşük Banka 1',
            'P0422'=>'Ana Katalitik Konvertör Verimliliği Düşük Banka 1',
            'P0423'=>'Isıtmalı Katalitik Konvertör Verimliliği Düşük Banka 1',
            'P0424'=>'Isıtmalı Katalitik Konvertör Sıcaklık Düşük Banka 1',
            'P0425'=>'Katalitik Konvertör Sıcaklık Sensörü Banka 1 Sensör 1',
            'P0426'=>'Katalitik Konvertör Sıcaklık Sensörü Aralık/Performans Banka 1 Sensör 1',
            'P0427'=>'Katalitik Konvertör Sıcaklık Sensörü Düşük Banka 1 Sensör 1',
            'P0428'=>'Katalitik Konvertör Sıcaklık Sensörü Yüksek Banka 1 Sensör 1',
            'P0429'=>'Isıtmalı Katalitik Konvertör Isıtıcı Kontrol Devresi Banka 1',
            'P0430'=>'Katalitik Konvertör Sistem Verimliliği Düşük Banka 2',
            'P0431'=>'Isınma Katalitik Konvertör Verimliliği Düşük Banka 2',
            'P0432'=>'Ana Katalitik Konvertör Verimliliği Düşük Banka 2',
            'P0433'=>'Isıtmalı Katalitik Konvertör Verimliliği Düşük Banka 2',
            'P0434'=>'Isıtmalı Katalitik Konvertör Sıcaklık Düşük Banka 2',
            'P0440'=>'Buharlaşmalı Emisyon Kontrol Sistemi Arızası',
            'P0441'=>'Buharlaşmalı Emisyon Kontrol Sistemi Yanlış Tasfiye Akışı',
            'P0442'=>'Buharlaşmalı Emisyon Kontrol Sistemi Küçük Kaçak',
            'P0443'=>'Buharlaşmalı Emisyon Kontrol Sistemi Tasfiye Kontrol Valfi Devresi',
            'P0444'=>'Buharlaşmalı Emisyon Kontrol Sistemi Tasfiye Kontrol Valfi Devre Açık',
            'P0445'=>'Buharlaşmalı Emisyon Kontrol Sistemi Tasfiye Kontrol Valfi Devre Kısa',
            'P0446'=>'Buharlaşmalı Emisyon Kontrol Sistemi Havalandırma Kontrol Devresi',
            'P0447'=>'Buharlaşmalı Emisyon Kontrol Sistemi Havalandırma Kontrol Devresi Açık',
            'P0448'=>'Buharlaşmalı Emisyon Kontrol Sistemi Havalandırma Kontrol Devresi Kısa',
            'P0449'=>'Buharlaşmalı Emisyon Kontrol Sistemi Havalandırma Valfi/Solenoid Devre Arızası',
            'P0450'=>'Buharlaşmalı Emisyon Kontrol Sistemi Basınç Sensörü Arızası',
            'P0451'=>'Buharlaşmalı Emisyon Kontrol Sistemi Basınç Sensörü Aralık/Performans',
            'P0452'=>'Buharlaşmalı Emisyon Kontrol Sistemi Basınç Sensörü Düşük Giriş',
            'P0453'=>'Buharlaşmalı Emisyon Kontrol Sistemi Basınç Sensörü Yüksek Giriş',
            'P0454'=>'Buharlaşmalı Emisyon Kontrol Sistemi Basınç Sensörü Aralıklı',
            'P0455'=>'Buharlaşmalı Emisyon Kontrol Sistemi Büyük Kaçak',
            'P0456'=>'Buharlaşmalı Emisyon Kontrol Sistemi Çok Küçük Kaçak',
            'P0457'=>'Buharlaşmalı Emisyon Kontrol Sistemi Yakıt Deposu Kapağı Gevşek/Açık',
            'P0458'=>'Buharlaşmalı Emisyon Kontrol Sistemi Tasfiye Kontrol Valfi Devre Düşük',
            'P0459'=>'Buharlaşmalı Emisyon Kontrol Sistemi Tasfiye Kontrol Valfi Devre Yüksek',
            'P0460'=>'Yakıt Seviye Sensörü Devre Arızası',
            'P0461'=>'Yakıt Seviye Sensörü Aralık/Performans',
            'P0462'=>'Yakıt Seviye Sensörü Düşük Giriş',
            'P0463'=>'Yakıt Seviye Sensörü Yüksek Giriş',
            'P0464'=>'Yakıt Seviye Sensörü Aralıklı',
            'P0465'=>'Tasfiye Akış Sensörü Devre Arızası',
            'P0466'=>'Tasfiye Akış Sensörü Aralık/Performans',
            'P0467'=>'Tasfiye Akış Sensörü Düşük Giriş',
            'P0468'=>'Tasfiye Akış Sensörü Yüksek Giriş',
            'P0469'=>'Tasfiye Akış Sensörü Aralıklı',
            'P0470'=>'Egzoz Basınç Sensörü Arızası',
            'P0471'=>'Egzoz Basınç Sensörü Aralık/Performans',
            'P0472'=>'Egzoz Basınç Sensörü Düşük',
            'P0473'=>'Egzoz Basınç Sensörü Yüksek',
            'P0474'=>'Egzoz Basınç Sensörü Aralıklı',
            'P0475'=>'Egzoz Basınç Kontrol Valfi Arızası',
            'P0476'=>'Egzoz Basınç Kontrol Valfi Aralık/Performans',
            'P0477'=>'Egzoz Basınç Kontrol Valfi Düşük',
            'P0478'=>'Egzoz Basınç Kontrol Valfi Yüksek',
            'P0479'=>'Egzoz Basınç Kontrol Valfi Aralıklı',
            'P0480'=>'Soğutma Fanı 1 Kontrol Devresi Arızası',
            'P0481'=>'Soğutma Fanı 2 Kontrol Devresi Arızası',
            'P0482'=>'Soğutma Fanı 3 Kontrol Devresi Arızası',
            'P0483'=>'Soğutma Fanı Rasyonalite Kontrolü Arızası',
            'P0484'=>'Soğutma Fanı Devre Aşırı Akım',
            'P0485'=>'Soğutma Fanı Güç/Toprak Devre Arızası',
            'P0486'=>'Egzoz Gaz Sirkülasyon Sensörü B Devre Arızası',
            'P0487'=>'Egzoz Gaz Sirkülasyon Gaz Kelebeği Kontrol Devresi A',
            'P0488'=>'Egzoz Gaz Sirkülasyon Gaz Kelebeği Kontrol Devresi Aralık/Performans A',
            'P0489'=>'Egzoz Gaz Sirkülasyon Kontrol Devresi Düşük',
            'P0490'=>'Egzoz Gaz Sirkülasyon Kontrol Devresi Yüksek',
            'P0491'=>'İkincil Hava Enjeksiyon Sistemi Yetersiz Akış Banka 1',
            'P0492'=>'İkincil Hava Enjeksiyon Sistemi Yetersiz Akış Banka 2',
            'P0493'=>'Fan Aşırı Hız Banka 1',
            'P0494'=>'Fan Hızı Düşük Banka 1',
            'P0495'=>'Fan Hızı Yüksek Banka 1',
            'P0496'=>'Buharlaşmalı Emisyon Sistemi Yüksek Tasfiye Akışı',
            'P0497'=>'Buharlaşmalı Emisyon Sistemi Düşük Tasfiye Akışı',
            'P0498'=>'Buharlaşmalı Emisyon Sistemi Havalandırma Valfi Kontrol Devresi Düşük',
            'P0499'=>'Buharlaşmalı Emisyon Sistemi Havalandırma Valfi Kontrol Devresi Yüksek',
            // P05xx - Araç Hızı/Rölanti
            'P0500'=>'Araç Hız Sensörü Arızası',
            'P0501'=>'Araç Hız Sensörü Aralık/Performans',
            'P0502'=>'Araç Hız Sensörü Düşük Giriş',
            'P0503'=>'Araç Hız Sensörü Aralıklı/Hatalı/Yüksek',
            'P0504'=>'Fren Anahtarı A/B Korelasyonu',
            'P0505'=>'Rölanti Kontrol Sistemi Arızası',
            'P0506'=>'Rölanti Kontrol Sistemi RPM Düşük',
            'P0507'=>'Rölanti Kontrol Sistemi RPM Yüksek',
            'P0508'=>'Rölanti Kontrol Sistemi Devre Düşük',
            'P0509'=>'Rölanti Kontrol Sistemi Devre Yüksek',
            'P0510'=>'Kapalı Gaz Kelebeği Konum Anahtarı Arızası',
            'P0511'=>'Rölanti Hava Kontrol Devresi Arızası',
            'P0512'=>'Marş Talep Devresi Düşük',
            'P0513'=>'Yanlış Immobilizer Anahtarı',
            'P0514'=>'Batarya Sıcaklık Sensörü Devre Aralık/Performans',
            'P0515'=>'Batarya Sıcaklık Sensörü Devre Arızası',
            'P0516'=>'Batarya Sıcaklık Sensörü Devre Düşük',
            'P0517'=>'Batarya Sıcaklık Sensörü Devre Yüksek',
            'P0518'=>'Rölanti Hava Kontrol Devresi Aralıklı',
            'P0519'=>'Rölanti Hava Kontrol Sistemi Performans',
            'P0520'=>'Motor Yağ Basınç Sensörü/Anahtarı Devre Arızası',
            'P0521'=>'Motor Yağ Basınç Sensörü/Anahtarı Aralık/Performans',
            'P0522'=>'Motor Yağ Basınç Sensörü/Anahtarı Düşük Voltaj',
            'P0523'=>'Motor Yağ Basınç Sensörü/Anahtarı Yüksek Voltaj',
            'P0524'=>'Motor Yağ Basıncı Çok Düşük',
            'P0530'=>'A/C Soğutucu Basınç Sensörü Devre Arızası',
            'P0531'=>'A/C Soğutucu Basınç Sensörü Aralık/Performans',
            'P0532'=>'A/C Soğutucu Basınç Sensörü Düşük Giriş',
            'P0533'=>'A/C Soğutucu Basınç Sensörü Yüksek Giriş',
            'P0534'=>'A/C Soğutucu Şarjı Kaybı',
            'P0540'=>'Emme Havası Isıtıcı Devre A Arızası',
            'P0541'=>'Emme Havası Isıtıcı Devre A Düşük',
            'P0542'=>'Emme Havası Isıtıcı Devre A Yüksek',
            'P0543'=>'Emme Havası Isıtıcı Devre A Açık',
            'P0544'=>'Egzoz Gazı Sıcaklık Sensörü Devre Banka 1 Sensör 1',
            'P0545'=>'Egzoz Gazı Sıcaklık Sensörü Devre Düşük Banka 1 Sensör 1',
            'P0546'=>'Egzoz Gazı Sıcaklık Sensörü Devre Yüksek Banka 1 Sensör 1',
            'P0547'=>'Egzoz Gazı Sıcaklık Sensörü Devre Banka 2 Sensör 1',
            'P0548'=>'Egzoz Gazı Sıcaklık Sensörü Devre Düşük Banka 2 Sensör 1',
            'P0549'=>'Egzoz Gazı Sıcaklık Sensörü Devre Yüksek Banka 2 Sensör 1',
            'P0550'=>'Güç Direksiyon Basınç Sensörü/Anahtarı Devre Arızası',
            'P0551'=>'Güç Direksiyon Basınç Sensörü/Anahtarı Aralık/Performans',
            'P0552'=>'Güç Direksiyon Basınç Sensörü/Anahtarı Düşük Giriş',
            'P0553'=>'Güç Direksiyon Basınç Sensörü/Anahtarı Yüksek Giriş',
            'P0554'=>'Güç Direksiyon Basınç Sensörü/Anahtarı Aralıklı',
            'P0560'=>'Sistem Voltajı Arızası',
            'P0561'=>'Sistem Voltajı Kararsız',
            'P0562'=>'Sistem Voltajı Düşük',
            'P0563'=>'Sistem Voltajı Yüksek',
            'P0564'=>'Hız Sabitleyici Çok Fonksiyonlu Giriş A Devre Arızası',
            'P0565'=>'Hız Sabitleyici Açık Sinyal Arızası',
            'P0566'=>'Hız Sabitleyici Kapalı Sinyal Arızası',
            'P0567'=>'Hız Sabitleyici Devam Sinyal Arızası',
            'P0568'=>'Hız Sabitleyici Ayar Sinyal Arızası',
            'P0569'=>'Hız Sabitleyici Kıyı Sinyal Arızası',
            'P0570'=>'Hız Sabitleyici İvme Sinyal Arızası',
            'P0571'=>'Fren Anahtarı A Devre Arızası',
            'P0572'=>'Fren Anahtarı A Devre Düşük',
            'P0573'=>'Fren Anahtarı A Devre Yüksek',
            'P0574'=>'Hız Sabitleyici Sistemi - Araç Hızı Çok Yüksek',
            'P0575'=>'Hız Sabitleyici Giriş Devresi Arızası',
            'P0576'=>'Hız Sabitleyici Giriş Devresi Düşük',
            'P0577'=>'Hız Sabitleyici Giriş Devresi Yüksek',
            'P0578'=>'Hız Sabitleyici Çok Fonksiyonlu Giriş A Devre Takılı',
            'P0579'=>'Hız Sabitleyici Çok Fonksiyonlu Giriş A Devre Aralık/Performans',
            'P0580'=>'Hız Sabitleyici Çok Fonksiyonlu Giriş A Devre Düşük',
            'P0581'=>'Hız Sabitleyici Çok Fonksiyonlu Giriş A Devre Yüksek',
            'P0582'=>'Hız Sabitleyici Vakum Kontrol Devresi Açık',
            'P0583'=>'Hız Sabitleyici Vakum Kontrol Devresi Düşük',
            'P0584'=>'Hız Sabitleyici Vakum Kontrol Devresi Yüksek',
            'P0585'=>'Hız Sabitleyici Çok Fonksiyonlu Giriş A/B Korelasyonu',
            'P0586'=>'Hız Sabitleyici Havalandırma Kontrol Devresi Açık',
            'P0587'=>'Hız Sabitleyici Havalandırma Kontrol Devresi Düşük',
            'P0588'=>'Hız Sabitleyici Havalandırma Kontrol Devresi Yüksek',
            'P0589'=>'Hız Sabitleyici Çok Fonksiyonlu Giriş B Devre Arızası',
            'P0590'=>'Hız Sabitleyici Çok Fonksiyonlu Giriş B Devre Takılı',
            'P0591'=>'Hız Sabitleyici Çok Fonksiyonlu Giriş B Devre Aralık/Performans',
            'P0592'=>'Hız Sabitleyici Çok Fonksiyonlu Giriş B Devre Düşük',
            'P0593'=>'Hız Sabitleyici Çok Fonksiyonlu Giriş B Devre Yüksek',
            'P0594'=>'Hız Sabitleyici Servis Fren Devresi Açık',
            'P0595'=>'Hız Sabitleyici Servis Fren Devresi Düşük',
            'P0596'=>'Hız Sabitleyici Servis Fren Devresi Yüksek',
            'P0597'=>'Termostat Isıtıcı Kontrol Devresi Açık',
            'P0598'=>'Termostat Isıtıcı Kontrol Devresi Düşük',
            'P0599'=>'Termostat Isıtıcı Kontrol Devresi Yüksek',
        ];
    }

    private static function p_codes_4() {
        return [
            // P06xx - Bilgisayar/Çıkış Devresi
            'P0600'=>'Seri İletişim Bağlantısı Arızası',
            'P0601'=>'İç Kontrol Modülü Bellek Kontrol Toplamı Hatası',
            'P0602'=>'Kontrol Modülü Programlama Hatası',
            'P0603'=>'İç Kontrol Modülü KAM Hatası',
            'P0604'=>'İç Kontrol Modülü RAM Hatası',
            'P0605'=>'İç Kontrol Modülü ROM Hatası',
            'P0606'=>'PCM İşlemci Arızası',
            'P0607'=>'Kontrol Modülü Performans',
            'P0608'=>'Kontrol Modülü VSS Çıkış Devresi A Düşük',
            'P0609'=>'Kontrol Modülü VSS Çıkış Devresi A Yüksek',
            'P0610'=>'Kontrol Modülü Araç Seçenekleri Hatası',
            'P0611'=>'Yakıt Enjektör Kontrol Modülü Performans',
            'P0612'=>'Yakıt Enjektör Kontrol Modülü Röle Kontrol Devresi',
            'P0613'=>'TCM İşlemci Arızası',
            'P0614'=>'ECM/TCM Uyumsuz',
            'P0615'=>'Marş Rölesi Devresi Arızası',
            'P0616'=>'Marş Rölesi Devresi Düşük',
            'P0617'=>'Marş Rölesi Devresi Yüksek',
            'P0618'=>'Alternatif Yakıt Kontrol Modülü KAM Hatası',
            'P0619'=>'Alternatif Yakıt Kontrol Modülü RAM/ROM Hatası',
            'P0620'=>'Jeneratör Kontrol Devresi Arızası',
            'P0621'=>'Jeneratör Lamba L Devre Arızası',
            'P0622'=>'Jeneratör Alan F Kontrol Devresi Arızası',
            'P0623'=>'Jeneratör Lamba Kontrol Devresi Arızası',
            'P0624'=>'Yakıt Deposu Kapağı Lamba Kontrol Devresi Arızası',
            'P0625'=>'Jeneratör Alan Terminal Düşük',
            'P0626'=>'Jeneratör Alan Terminal Yüksek',
            'P0627'=>'Yakıt Pompası A Kontrol Devresi Açık',
            'P0628'=>'Yakıt Pompası A Kontrol Devresi Düşük',
            'P0629'=>'Yakıt Pompası A Kontrol Devresi Yüksek',
            'P0630'=>'VIN Programlanmamış ECM/PCM',
            'P0631'=>'VIN Programlanmamış TCM',
            'P0632'=>'Kilometre Sayacı Programlanmamış ECM/PCM',
            'P0633'=>'Immobilizer Anahtarı Programlanmamış ECM/PCM',
            'P0634'=>'PCM/ECM/TCM Dahili Sıcaklık Çok Yüksek',
            'P0635'=>'Güç Direksiyon Kontrol Devresi Arızası',
            'P0636'=>'Güç Direksiyon Kontrol Devresi Düşük',
            'P0637'=>'Güç Direksiyon Kontrol Devresi Yüksek',
            'P0638'=>'Gaz Kelebeği Aktüatör Kontrol Aralık/Performans Banka 1',
            'P0639'=>'Gaz Kelebeği Aktüatör Kontrol Aralık/Performans Banka 2',
            'P0640'=>'Emme Havası Isıtıcı Kontrol Devresi Arızası',
            'P0641'=>'Sensör Referans Voltajı A Devre Açık',
            'P0642'=>'Sensör Referans Voltajı A Devre Düşük',
            'P0643'=>'Sensör Referans Voltajı A Devre Yüksek',
            'P0644'=>'Sürücü Bilgi Ekranı Seri İletişim Devresi Arızası',
            'P0645'=>'A/C Debriyaj Rölesi Kontrol Devresi Açık',
            'P0646'=>'A/C Debriyaj Rölesi Kontrol Devresi Düşük',
            'P0647'=>'A/C Debriyaj Rölesi Kontrol Devresi Yüksek',
            'P0648'=>'Immobilizer Lamba Kontrol Devresi Arızası',
            'P0649'=>'Hız Sabitleyici Lamba Kontrol Devresi Arızası',
            'P0650'=>'Arıza Gösterge Lambası MIL Kontrol Devresi Arızası',
            'P0651'=>'Sensör Referans Voltajı B Devre Açık',
            'P0652'=>'Sensör Referans Voltajı B Devre Düşük',
            'P0653'=>'Sensör Referans Voltajı B Devre Yüksek',
            'P0654'=>'Motor Devir Çıkış Devresi Arızası',
            'P0655'=>'Motor Sıcak Lamba Çıkış Kontrol Devresi Arızası',
            'P0656'=>'Yakıt Seviye Çıkış Devresi Arızası',
            'P0657'=>'Aktüatör Besleme Voltajı A Devre Açık',
            'P0658'=>'Aktüatör Besleme Voltajı A Devre Düşük',
            'P0659'=>'Aktüatör Besleme Voltajı A Devre Yüksek',
            'P0660'=>'Emme Manifold Ayar Valfi Kontrol Devresi Açık Banka 1',
            'P0661'=>'Emme Manifold Ayar Valfi Kontrol Devresi Düşük Banka 1',
            'P0662'=>'Emme Manifold Ayar Valfi Kontrol Devresi Yüksek Banka 1',
            'P0663'=>'Emme Manifold Ayar Valfi Kontrol Devresi Açık Banka 2',
            'P0664'=>'Emne Manifold Ayar Valfi Kontrol Devresi Düşük Banka 2',
            'P0665'=>'Emme Manifold Ayar Valfi Kontrol Devresi Yüksek Banka 2',
            'P0666'=>'PCM/ECM/TCM Dahili Sıcaklık Sensörü Devre Arızası',
            'P0667'=>'PCM/ECM/TCM Dahili Sıcaklık Sensörü Aralık/Performans',
            'P0668'=>'PCM/ECM/TCM Dahili Sıcaklık Sensörü Düşük',
            'P0669'=>'PCM/ECM/TCM Dahili Sıcaklık Sensörü Yüksek',
            'P0670'=>'Glow Plug Modül Kontrol Devresi Arızası',
            'P0671'=>'1. Silindir Glow Plug Devresi Arızası',
            'P0672'=>'2. Silindir Glow Plug Devresi Arızası',
            'P0673'=>'3. Silindir Glow Plug Devresi Arızası',
            'P0674'=>'4. Silindir Glow Plug Devresi Arızası',
            'P0675'=>'5. Silindir Glow Plug Devresi Arızası',
            'P0676'=>'6. Silindir Glow Plug Devresi Arızası',
            'P0677'=>'7. Silindir Glow Plug Devresi Arızası',
            'P0678'=>'8. Silindir Glow Plug Devresi Arızası',
            'P0679'=>'9. Silindir Glow Plug Devresi Arızası',
            'P0680'=>'10. Silindir Glow Plug Devresi Arızası',
            'P0681'=>'11. Silindir Glow Plug Devresi Arızası',
            'P0682'=>'12. Silindir Glow Plug Devresi Arızası',
            'P0683'=>'Glow Plug Kontrol Modülü PCM İletişim Devresi Arızası',
            'P0684'=>'Glow Plug Kontrol Modülü PCM İletişim Devresi Aralık/Performans',
            'P0685'=>'ECM/PCM Güç Rölesi Kontrol Devresi Açık',
            'P0686'=>'ECM/PCM Güç Rölesi Kontrol Devresi Düşük',
            'P0687'=>'ECM/PCM Güç Rölesi Kontrol Devresi Yüksek',
            'P0688'=>'ECM/PCM Güç Rölesi Algılama Devresi Açık',
            'P0689'=>'ECM/PCM Güç Rölesi Algılama Devresi Düşük',
            'P0690'=>'ECM/PCM Güç Rölesi Algılama Devresi Yüksek',
            'P0691'=>'Soğutma Fanı 1 Kontrol Devresi Düşük',
            'P0692'=>'Soğutma Fanı 1 Kontrol Devresi Yüksek',
            'P0693'=>'Soğutma Fanı 2 Kontrol Devresi Düşük',
            'P0694'=>'Soğutma Fanı 2 Kontrol Devresi Yüksek',
            'P0695'=>'Soğutma Fanı 3 Kontrol Devresi Düşük',
            'P0696'=>'Soğutma Fanı 3 Kontrol Devresi Yüksek',
            'P0697'=>'Sensör Referans Voltajı C Devre Açık',
            'P0698'=>'Sensör Referans Voltajı C Devre Düşük',
            'P0699'=>'Sensör Referans Voltajı C Devre Yüksek',
            // P07xx - Şanzıman
            'P0700'=>'Şanzıman Kontrol Sistemi Arızası',
            'P0701'=>'Şanzıman Kontrol Sistemi Aralık/Performans',
            'P0702'=>'Şanzıman Kontrol Sistemi Elektrik Arızası',
            'P0703'=>'Tork Konvertörü/Fren Anahtarı B Devre Arızası',
            'P0704'=>'Debriyaj Anahtarı Giriş Devresi Arızası',
            'P0705'=>'Şanzıman Aralık Sensörü Devresi Arızası PRNDL Girişi',
            'P0706'=>'Şanzıman Aralık Sensörü Devresi Aralık/Performans',
            'P0707'=>'Şanzıman Aralık Sensörü Devresi Düşük Giriş',
            'P0708'=>'Şanzıman Aralık Sensörü Devresi Yüksek Giriş',
            'P0709'=>'Şanzıman Aralık Sensörü Devresi Aralıklı',
            'P0710'=>'Şanzıman Sıvı Sıcaklık Sensörü Devre Arızası',
            'P0711'=>'Şanzıman Sıvı Sıcaklık Sensörü Aralık/Performans',
            'P0712'=>'Şanzıman Sıvı Sıcaklık Sensörü Düşük Giriş',
            'P0713'=>'Şanzıman Sıvı Sıcaklık Sensörü Yüksek Giriş',
            'P0714'=>'Şanzıman Sıvı Sıcaklık Sensörü Aralıklı',
            'P0715'=>'Giriş/Türbin Hız Sensörü Devre Arızası',
            'P0716'=>'Giriş/Türbin Hız Sensörü Devre Aralık/Performans',
            'P0717'=>'Giriş/Türbin Hız Sensörü Devre Sinyal Yok',
            'P0718'=>'Giriş/Türbin Hız Sensörü Devre Aralıklı',
            'P0719'=>'Tork Konvertörü/Fren Anahtarı B Devre Düşük',
            'P0720'=>'Çıkış Hız Sensörü Devre Arızası',
            'P0721'=>'Çıkış Hız Sensörü Aralık/Performans',
            'P0722'=>'Çıkış Hız Sensörü Sinyal Yok',
            'P0723'=>'Çıkış Hız Sensörü Aralıklı',
            'P0724'=>'Tork Konvertörü/Fren Anahtarı B Devre Yüksek',
            'P0725'=>'Motor Hız Giriş Devresi Arızası',
            'P0726'=>'Motor Hız Giriş Devresi Aralık/Performans',
            'P0727'=>'Motor Hız Giriş Devresi Sinyal Yok',
            'P0728'=>'Motor Hız Giriş Devresi Aralıklı',
            'P0729'=>'6. Vites Oranı Yanlış',
            'P0730'=>'Yanlış Vites Oranı',
            'P0731'=>'1. Vites Oranı Yanlış',
            'P0732'=>'2. Vites Oranı Yanlış',
            'P0733'=>'3. Vites Oranı Yanlış',
            'P0734'=>'4. Vites Oranı Yanlış',
            'P0735'=>'5. Vites Oranı Yanlış',
            'P0736'=>'Geri Vites Oranı Yanlış',
            'P0740'=>'Tork Konvertörü Debriyaj Solenoid Devre Arızası',
            'P0741'=>'Tork Konvertörü Debriyaj Solenoid Performans veya Takılı Kapalı',
            'P0742'=>'Tork Konvertörü Debriyaj Solenoid Takılı Açık',
            'P0743'=>'Tork Konvertörü Debriyaj Solenoid Elektrik Arızası',
            'P0744'=>'Tork Konvertörü Debriyaj Solenoid Aralıklı',
            'P0745'=>'Basınç Kontrol Solenoid Arızası',
            'P0746'=>'Basınç Kontrol Solenoid Performans veya Takılı Kapalı',
            'P0747'=>'Basınç Kontrol Solenoid Takılı Açık',
            'P0748'=>'Basınç Kontrol Solenoid Elektrik Arızası',
            'P0749'=>'Basınç Kontrol Solenoid Aralıklı',
            'P0750'=>'Vites Solenoid A Arızası',
            'P0751'=>'Vites Solenoid A Performans veya Takılı Kapalı',
            'P0752'=>'Vites Solenoid A Takılı Açık',
            'P0753'=>'Vites Solenoid A Elektrik Arızası',
            'P0754'=>'Vites Solenoid A Aralıklı',
            'P0755'=>'Vites Solenoid B Arızası',
            'P0756'=>'Vites Solenoid B Performans veya Takılı Kapalı',
            'P0757'=>'Vites Solenoid B Takılı Açık',
            'P0758'=>'Vites Solenoid B Elektrik Arızası',
            'P0759'=>'Vites Solenoid B Aralıklı',
            'P0760'=>'Vites Solenoid C Arızası',
            'P0761'=>'Vites Solenoid C Performans veya Takılı Kapalı',
            'P0762'=>'Vites Solenoid C Takılı Açık',
            'P0763'=>'Vites Solenoid C Elektrik Arızası',
            'P0764'=>'Vites Solenoid C Aralıklı',
            'P0765'=>'Vites Solenoid D Arızası',
            'P0766'=>'Vites Solenoid D Performans veya Takılı Kapalı',
            'P0767'=>'Vites Solenoid D Takılı Açık',
            'P0768'=>'Vites Solenoid D Elektrik Arızası',
            'P0769'=>'Vites Solenoid D Aralıklı',
            'P0770'=>'Vites Solenoid E Arızası',
            'P0771'=>'Vites Solenoid E Performans veya Takılı Kapalı',
            'P0772'=>'Vites Solenoid E Takılı Açık',
            'P0773'=>'Vites Solenoid E Elektrik Arızası',
            'P0774'=>'Vites Solenoid E Aralıklı',
            'P0775'=>'Basınç Kontrol Solenoid B Arızası',
            'P0776'=>'Basınç Kontrol Solenoid B Performans veya Takılı Kapalı',
            'P0777'=>'Basınç Kontrol Solenoid B Takılı Açık',
            'P0778'=>'Basınç Kontrol Solenoid B Elektrik Arızası',
            'P0779'=>'Basınç Kontrol Solenoid B Aralıklı',
            'P0780'=>'Vites Arızası',
            'P0781'=>'1-2 Vites Arızası',
            'P0782'=>'2-3 Vites Arızası',
            'P0783'=>'3-4 Vites Arızası',
            'P0784'=>'4-5 Vites Arızası',
            'P0785'=>'Vites/Başlangıç Solenoid Arızası',
            'P0786'=>'Vites/Başlangıç Solenoid Aralık/Performans',
            'P0787'=>'Vites/Başlangıç Solenoid Düşük',
            'P0788'=>'Vites/Başlangıç Solenoid Yüksek',
            'P0789'=>'Vites/Başlangıç Solenoid Aralıklı',
            'P0790'=>'Normal/Performans Anahtarı Devre Arızası',
            'P0791'=>'Ara Mil Hız Sensörü Devre Arızası',
            'P0792'=>'Ara Mil Hız Sensörü Devre Aralık/Performans',
            'P0793'=>'Ara Mil Hız Sensörü Devre Sinyal Yok',
            'P0794'=>'Ara Mil Hız Sensörü Devre Aralıklı',
            'P0795'=>'Basınç Kontrol Solenoid C Arızası',
            'P0796'=>'Basınç Kontrol Solenoid C Performans veya Takılı Kapalı',
            'P0797'=>'Basınç Kontrol Solenoid C Takılı Açık',
            'P0798'=>'Basınç Kontrol Solenoid C Elektrik Arızası',
            'P0799'=>'Basınç Kontrol Solenoid C Aralıklı',
        ];
    }

    private static function p_codes_5() {
        return [
            // P08xx - Transfer Kutusu
            'P0800'=>'Transfer Kutusu Kontrol Sistemi Arızası',
            'P0801'=>'Geri Vites Devre Arızası',
            'P0802'=>'Şanzıman Kontrol Sistemi MIL Talep Devresi Açık',
            'P0803'=>'1-4 Vites Solenoid Arızası',
            'P0804'=>'1-4 Vites Gösterge Devre Arızası',
            'P0805'=>'Debriyaj Konum Sensörü Devre Arızası',
            'P0806'=>'Debriyaj Konum Sensörü Devre Aralık/Performans',
            'P0807'=>'Debriyaj Konum Sensörü Devre Düşük',
            'P0808'=>'Debriyaj Konum Sensörü Devre Yüksek',
            'P0809'=>'Debriyaj Konum Sensörü Devre Aralıklı',
            'P0810'=>'Debriyaj Konum Kontrol Hatası',
            'P0811'=>'Aşırı Debriyaj Kayması',
            'P0812'=>'Geri Vites Giriş Devresi Arızası',
            'P0813'=>'Geri Vites Çıkış Devresi Arızası',
            'P0814'=>'Şanzıman Aralık Ekranı Devre Arızası',
            'P0815'=>'Yukarı Vites Anahtarı Devre Arızası',
            'P0816'=>'Aşağı Vites Anahtarı Devre Arızası',
            'P0817'=>'Marş Devre Arızası',
            'P0818'=>'Driveline Bağlantısı Kesme Anahtarı Giriş Devresi Arızası',
            'P0819'=>'Yukarı/Aşağı Vites Anahtarı Şanzıman Aralık Korelasyonu',
            'P0820'=>'Vites Seçici X-Y Sensörü Devre Arızası',
            'P0821'=>'Vites Seçici X Sensörü Devre Aralık/Performans',
            'P0822'=>'Vites Seçici X Sensörü Devre Düşük',
            'P0823'=>'Vites Seçici X Sensörü Devre Yüksek',
            'P0824'=>'Vites Seçici X Sensörü Devre Aralıklı',
            'P0825'=>'Vites Seçici İtme/Çekme Anahtarı Devre Arızası',
            'P0826'=>'Yukarı/Aşağı Vites Anahtarı Giriş Devresi Arızası',
            'P0827'=>'Yukarı/Aşağı Vites Anahtarı Giriş Devresi Düşük',
            'P0828'=>'Yukarı/Aşağı Vites Anahtarı Giriş Devresi Yüksek',
            'P0829'=>'5-6 Vites Arızası',
            'P0830'=>'Debriyaj Pedal Anahtarı A Devre Arızası',
            'P0831'=>'Debriyaj Pedal Anahtarı A Devre Düşük',
            'P0832'=>'Debriyaj Pedal Anahtarı A Devre Yüksek',
            'P0833'=>'Debriyaj Pedal Anahtarı B Devre Arızası',
            'P0834'=>'Debriyaj Pedal Anahtarı B Devre Düşük',
            'P0835'=>'Debriyaj Pedal Anahtarı B Devre Yüksek',
            'P0836'=>'Dört Tekerlekten Çekiş Anahtarı Devre Arızası',
            'P0837'=>'Dört Tekerlekten Çekiş Anahtarı Devre Aralık/Performans',
            'P0838'=>'Dört Tekerlekten Çekiş Anahtarı Devre Düşük',
            'P0839'=>'Dört Tekerlekten Çekiş Anahtarı Devre Yüksek',
            'P0840'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı A Devre Arızası',
            'P0841'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı A Aralık/Performans',
            'P0842'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı A Düşük',
            'P0843'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı A Yüksek',
            'P0844'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı A Aralıklı',
            'P0845'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı B Devre Arızası',
            'P0846'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı B Aralık/Performans',
            'P0847'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı B Düşük',
            'P0848'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı B Yüksek',
            'P0849'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı B Aralıklı',
            'P0850'=>'Park/Nötr Konum Anahtarı Giriş Devresi Arızası',
            'P0851'=>'Park/Nötr Konum Anahtarı Giriş Devresi Düşük',
            'P0852'=>'Park/Nötr Konum Anahtarı Giriş Devresi Yüksek',
            'P0853'=>'Sürüş Modu Anahtarı Giriş Devresi Arızası',
            'P0854'=>'Sürüş Modu Anahtarı Giriş Devresi Düşük',
            'P0855'=>'Sürüş Modu Anahtarı Giriş Devresi Yüksek',
            'P0856'=>'Tork Talep Sinyali Devre Arızası',
            'P0857'=>'Tork Talep Sinyali Devre Aralık/Performans',
            'P0858'=>'Tork Talep Sinyali Devre Düşük',
            'P0859'=>'Tork Talep Sinyali Devre Yüksek',
            'P0860'=>'Vites Seçici Modülü İletişim Devresi Arızası',
            'P0861'=>'Vites Seçici Modülü İletişim Devresi Düşük',
            'P0862'=>'Vites Seçici Modülü İletişim Devresi Yüksek',
            'P0863'=>'TCM İletişim Devresi Arızası',
            'P0864'=>'TCM İletişim Devresi Aralık/Performans',
            'P0865'=>'TCM İletişim Devresi Düşük',
            'P0866'=>'TCM İletişim Devresi Yüksek',
            'P0867'=>'Şanzıman Sıvı Basıncı',
            'P0868'=>'Şanzıman Sıvı Basıncı Düşük',
            'P0869'=>'Şanzıman Sıvı Basıncı Yüksek',
            'P0870'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı C Devre Arızası',
            'P0871'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı C Aralık/Performans',
            'P0872'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı C Düşük',
            'P0873'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı C Yüksek',
            'P0874'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı C Aralıklı',
            'P0875'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı D Devre Arızası',
            'P0876'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı D Aralık/Performans',
            'P0877'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı D Düşük',
            'P0878'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı D Yüksek',
            'P0879'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı D Aralıklı',
            'P0880'=>'TCM Güç Giriş Sinyali Arızası',
            'P0881'=>'TCM Güç Giriş Sinyali Aralık/Performans',
            'P0882'=>'TCM Güç Giriş Sinyali Düşük',
            'P0883'=>'TCM Güç Giriş Sinyali Yüksek',
            'P0884'=>'TCM Güç Giriş Sinyali Aralıklı',
            'P0885'=>'TCM Güç Rölesi Kontrol Devresi Açık',
            'P0886'=>'TCM Güç Rölesi Kontrol Devresi Düşük',
            'P0887'=>'TCM Güç Rölesi Kontrol Devresi Yüksek',
            'P0888'=>'TCM Güç Rölesi Algılama Devresi Arızası',
            'P0889'=>'TCM Güç Rölesi Algılama Devresi Aralık/Performans',
            'P0890'=>'TCM Güç Rölesi Algılama Devresi Düşük',
            'P0891'=>'TCM Güç Rölesi Algılama Devresi Yüksek',
            'P0892'=>'TCM Güç Rölesi Algılama Devresi Aralıklı',
            'P0893'=>'Birden Fazla Vites Takılı',
            'P0894'=>'Şanzıman Bileşen Kayması',
            'P0895'=>'Vites Değiştirme Çok Hızlı',
            'P0896'=>'Vites Değiştirme Çok Yavaş',
            'P0897'=>'Şanzıman Sıvısı Değişim Gerekli',
            'P0898'=>'Şanzıman Kontrol Sistemi MIL Talep Devresi Düşük',
            'P0899'=>'Şanzıman Kontrol Sistemi MIL Talep Devresi Yüksek',
            // P09xx - Debriyaj
            'P0900'=>'Debriyaj Aktüatör Devre Açık',
            'P0901'=>'Debriyaj Aktüatör Devre Aralık/Performans',
            'P0902'=>'Debriyaj Aktüatör Devre Düşük',
            'P0903'=>'Debriyaj Aktüatör Devre Yüksek',
            'P0904'=>'Vites Seçici Konum Devre Arızası',
            'P0905'=>'Vites Seçici Konum Devre Aralık/Performans',
            'P0906'=>'Vites Seçici Konum Devre Düşük',
            'P0907'=>'Vites Seçici Konum Devre Yüksek',
            'P0908'=>'Vites Seçici Konum Devre Aralıklı',
            'P0909'=>'Vites Seçici Kontrol Hatası',
            'P0910'=>'Vites Seçici Aktüatör Devre Açık',
            'P0911'=>'Vites Seçici Aktüatör Devre Aralık/Performans',
            'P0912'=>'Vites Seçici Aktüatör Devre Düşük',
            'P0913'=>'Vites Seçici Aktüatör Devre Yüksek',
            'P0914'=>'Vites Değiştirme Konum Devre Arızası',
            'P0915'=>'Vites Değiştirme Konum Devre Aralık/Performans',
            'P0916'=>'Vites Değiştirme Konum Devre Düşük',
            'P0917'=>'Vites Değiştirme Konum Devre Yüksek',
            'P0918'=>'Vites Değiştirme Konum Devre Aralıklı',
            'P0919'=>'Vites Değiştirme Konum Kontrol Hatası',
            'P0920'=>'Vites Değiştirme Aktüatör Devre Açık İleri',
            'P0921'=>'Vites Değiştirme Aktüatör Devre Aralık/Performans İleri',
            'P0922'=>'Vites Değiştirme Aktüatör Devre Düşük İleri',
            'P0923'=>'Vites Değiştirme Aktüatör Devre Yüksek İleri',
            'P0924'=>'Vites Değiştirme Aktüatör Devre Açık Geri',
            'P0925'=>'Vites Değiştirme Aktüatör Devre Aralık/Performans Geri',
            'P0926'=>'Vites Değiştirme Aktüatör Devre Düşük Geri',
            'P0927'=>'Vites Değiştirme Aktüatör Devre Yüksek Geri',
            'P0928'=>'Vites Seçici Kilitleme Solenoid Kontrol Devresi Açık',
            'P0929'=>'Vites Seçici Kilitleme Solenoid Kontrol Devresi Düşük',
            'P0930'=>'Vites Seçici Kilitleme Solenoid Kontrol Devresi Yüksek',
            'P0931'=>'Vites Seçici Kilitleme Solenoid Kontrol Devresi Aralık/Performans',
            'P0932'=>'Hidrolik Basınç Sensörü Devre Arızası',
            'P0933'=>'Hidrolik Basınç Sensörü Devre Aralık/Performans',
            'P0934'=>'Hidrolik Basınç Sensörü Devre Düşük',
            'P0935'=>'Hidrolik Basınç Sensörü Devre Yüksek',
            'P0936'=>'Hidrolik Basınç Sensörü Devre Aralıklı',
            'P0944'=>'Hidrolik Basınç Birimi Basınç Kaybı',
            'P0945'=>'Hidrolik Pompa Rölesi Devre Açık',
            'P0946'=>'Hidrolik Pompa Rölesi Devre Aralık/Performans',
            'P0947'=>'Hidrolik Pompa Rölesi Devre Düşük',
            'P0948'=>'Hidrolik Pompa Rölesi Devre Yüksek',
            'P0961'=>'Basınç Kontrol Solenoid A Kontrol Aralık/Performans',
            'P0962'=>'Basınç Kontrol Solenoid A Kontrol Devresi Düşük',
            'P0963'=>'Basınç Kontrol Solenoid A Kontrol Devresi Yüksek',
            'P0964'=>'Basınç Kontrol Solenoid B Kontrol Aralık/Performans',
            'P0965'=>'Basınç Kontrol Solenoid B Kontrol Devresi Düşük',
            'P0966'=>'Basınç Kontrol Solenoid B Kontrol Devresi Yüksek',
            'P0967'=>'Basınç Kontrol Solenoid C Kontrol Aralık/Performans',
            'P0968'=>'Basınç Kontrol Solenoid C Kontrol Devresi Düşük',
            'P0969'=>'Basınç Kontrol Solenoid C Kontrol Devresi Yüksek',
            'P0970'=>'Basınç Kontrol Solenoid D Kontrol Aralık/Performans',
            'P0971'=>'Basınç Kontrol Solenoid D Kontrol Devresi Düşük',
            'P0972'=>'Vites Solenoid A Kontrol Aralık/Performans',
            'P0973'=>'Vites Solenoid A Kontrol Devresi Düşük',
            'P0974'=>'Vites Solenoid A Kontrol Devresi Yüksek',
            'P0975'=>'Vites Solenoid B Kontrol Aralık/Performans',
            'P0976'=>'Vites Solenoid B Kontrol Devresi Düşük',
            'P0977'=>'Vites Solenoid B Kontrol Devresi Yüksek',
            'P0978'=>'Vites Solenoid C Kontrol Aralık/Performans',
            'P0979'=>'Vites Solenoid C Kontrol Devresi Düşük',
            'P0980'=>'Vites Solenoid C Kontrol Devresi Yüksek',
            'P0981'=>'Vites Solenoid D Kontrol Aralık/Performans',
            'P0982'=>'Vites Solenoid D Kontrol Devresi Düşük',
            'P0983'=>'Vites Solenoid D Kontrol Devresi Yüksek',
            'P0984'=>'Vites Solenoid E Kontrol Aralık/Performans',
            'P0985'=>'Vites Solenoid E Kontrol Devresi Düşük',
            'P0986'=>'Vites Solenoid E Kontrol Devresi Yüksek',
            'P0987'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı E Devre Arızası',
            'P0988'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı E Aralık/Performans',
            'P0989'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı E Düşük',
            'P0990'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı E Yüksek',
            'P0991'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı E Aralıklı',
            'P0992'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı F Devre Arızası',
            'P0993'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı F Aralık/Performans',
            'P0994'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı F Düşük',
            'P0995'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı F Yüksek',
            'P0996'=>'Şanzıman Sıvı Basınç Sensörü/Anahtarı F Aralıklı',
            'P0997'=>'Vites Solenoid F Kontrol Aralık/Performans',
            'P0998'=>'Vites Solenoid F Kontrol Devresi Düşük',
            'P0999'=>'Vites Solenoid F Kontrol Devresi Yüksek',
        ];
    }

    private static function p_codes() {
        return array_merge(
            self::p_codes_1(),
            self::p_codes_2(),
            self::p_codes_3(),
            self::p_codes_4(),
            self::p_codes_5(),
            ak_p2_codes(),
            ak_p2b_codes(),
            ak_p2c_codes()
        );
    }

    private static function b_codes() {
        return ak_b_codes();
    }

    private static function c_codes() {
        return ak_c_codes();
    }

    private static function u_codes() {
        return ak_u_codes();
    }
}
