<?php
/** Template Name: Datenschutz */
$details = findewerkstatt_get_site_details();
get_header();
?>
<main id="main-content" class="fw-container fw-page-content">
    <article class="fw-box fw-form-wrap-wide">
        <h1><?php echo esc_html( findewerkstatt_t( 'Datenschutzerklärung' ) ); ?></h1>
        <?php get_template_part( 'template-parts/legal-navigation' ); ?>
        <div class="fw-prose">
            <p><?php echo esc_html( findewerkstatt_t( 'FindeWerkstatt.de ist ein Verzeichnis von Kfz-Werkstätten und Autoservices in Deutschland. Hier erfahren Sie, welche Daten wir beim Besuch der Website, bei Anfragen und bei der Pflege von Firmenprofilen verarbeiten.' ) ); ?></p>

            <nav class="fw-legal-contents" aria-label="<?php echo esc_attr( findewerkstatt_t( 'Inhaltsverzeichnis der Datenschutzerklärung' ) ); ?>">
                <p><strong><?php echo esc_html( findewerkstatt_t( 'Inhalt' ) ); ?></strong></p>
                <ul>
                    <li><a href="#verantwortlicher"><?php echo esc_html( findewerkstatt_t( '1. Verantwortlicher und Kontakt' ) ); ?></a></li>
                    <li><a href="#website-hosting"><?php echo esc_html( findewerkstatt_t( '2. Website-Aufruf und Hosting' ) ); ?></a></li>
                    <li><a href="#kontakt-mail"><?php echo esc_html( findewerkstatt_t( '3. Kontaktformular und E-Mail' ) ); ?></a></li>
                    <li><a href="#werkstattanmeldung"><?php echo esc_html( findewerkstatt_t( '4. Werkstattanmeldung und Veröffentlichung' ) ); ?></a></li>
                    <li><a href="#bestehende-firmendaten"><?php echo esc_html( findewerkstatt_t( '5. Firmendaten aus Google Maps und Löschung' ) ); ?></a></li>
                    <li><a href="#cookies-formularschutz"><?php echo esc_html( findewerkstatt_t( '6. Cookies und Formularschutz' ) ); ?></a></li>
                    <li><a href="#externe-dienste"><?php echo esc_html( findewerkstatt_t( '7. Google Maps, WhatsApp und externe Links' ) ); ?></a></li>
                    <li><a href="#datenschutzrechte"><?php echo esc_html( findewerkstatt_t( '8. Ihre Datenschutzrechte' ) ); ?></a></li>
                    <li><a href="#widerspruch"><?php echo esc_html( findewerkstatt_t( '9. Widerspruch nach Art. 21 DSGVO' ) ); ?></a></li>
                    <li><a href="#werkstattkonto"><?php echo esc_html( findewerkstatt_t( '10. Werkstattkonto und Paketanfragen' ) ); ?></a></li>
                </ul>
            </nav>

            <h2 id="verantwortlicher"><?php echo esc_html( findewerkstatt_t( '1. Verantwortlicher und Kontakt' ) ); ?></h2>
            <p><?php echo esc_html( findewerkstatt_t( 'Verantwortlich für die in dieser Erklärung beschriebenen Verarbeitungen ist:' ) ); ?></p>
            <p><?php echo esc_html( $details['name'] ); ?><br><?php echo nl2br( esc_html( $details['address'] ) ); ?><br>E-Mail: <a href="mailto:<?php echo esc_attr( $details['email'] ); ?>"><?php echo esc_html( $details['email'] ); ?></a></p>
            <p><?php echo esc_html( findewerkstatt_t( 'Für Datenschutzfragen sowie für die Berichtigung oder Entfernung von Einträgen können Sie uns per E-Mail oder über das' ) ); ?> <a href="<?php echo esc_url( findewerkstatt_page_url( 'kontakt' ) ); ?>"><?php echo esc_html( findewerkstatt_t( 'Kontaktformular' ) ); ?></a> <?php echo esc_html( findewerkstatt_t( 'erreichen. Nennen Sie bei Fragen zu einem Firmenprofil bitte den Betrieb und die betreffende Profiladresse.' ) ); ?></p>

            <h2 id="website-hosting"><?php echo esc_html( findewerkstatt_t( '2. Website-Aufruf und Hosting' ) ); ?></h2>
            <p><?php echo esc_html( findewerkstatt_t( 'Beim Aufruf der Website werden technische Zugriffsdaten verarbeitet, insbesondere Ihre IP-Adresse, die angeforderte Seite oder Datei und der Zeitpunkt des Zugriffs. Der eingesetzte Hosting-Dienst kann diese Angaben in Serverprotokollen erfassen. Die Verarbeitung ermöglicht die Auslieferung der Website, die Fehlerbehebung und den Schutz vor missbräuchlichen Zugriffen. Sie beruht auf unserem berechtigten Interesse an einem erreichbaren und sicheren Verzeichnis nach Art. 6 Abs. 1 Buchst. f DSGVO.' ) ); ?></p>
            <p><?php echo esc_html( findewerkstatt_t( 'Bei der Werkstattsuche werden Ihre Suchbegriffe und gewählten Filter verarbeitet, um passende Betriebe anzuzeigen. Diese Angaben können als Bestandteil der angeforderten Adresse auch in technischen Zugriffsprotokollen enthalten sein.' ) ); ?></p>
            <?php if ( ! empty( $details['hosting'] ) ) : ?>
                <p><strong><?php echo esc_html( findewerkstatt_t( 'Hosting und Ort der Datenverarbeitung:' ) ); ?></strong><br><?php echo nl2br( esc_html( $details['hosting'] ) ); ?></p>
            <?php else : ?>
                <p><?php echo esc_html( findewerkstatt_t( 'Auskünfte zum eingesetzten Hosting-Dienstleister und zum Ort der Datenverarbeitung erhalten Sie über die in Abschnitt 1 genannte Kontaktadresse.' ) ); ?></p>
            <?php endif; ?>
            <p><?php echo esc_html( findewerkstatt_t( 'Serverprotokolle werden benötigt, solange sie zur Fehleranalyse, zum sicheren Betrieb oder zur Aufklärung eines konkreten Sicherheitsvorfalls erforderlich sind. Sicherungskopien dienen der Wiederherstellung der Website; ihre Aufbewahrung richtet sich nach dem verwendeten Sicherungszyklus. Hosting- und gegebenenfalls Maildienstleister können Daten verarbeiten, soweit dies für den Betrieb und den Versand von Nachrichten erforderlich ist.' ) ); ?></p>

            <h2 id="kontakt-mail"><?php echo esc_html( findewerkstatt_t( '3. Kontaktformular und E-Mail' ) ); ?></h2>
            <p><?php echo esc_html( findewerkstatt_t( 'Im Kontaktformular benötigen wir Ihren Namen, Ihre E-Mail-Adresse und Ihre Nachricht; der Betreff ist optional. Wir speichern außerdem den Zeitpunkt Ihrer Bestätigung des Datenschutzhinweises. Diese Angaben dienen der Bearbeitung Ihrer Anfrage. Bei einer vertragsbezogenen Anfrage oder gewünschten vorvertraglichen Maßnahme ist Art. 6 Abs. 1 Buchst. b DSGVO die Grundlage; bei sonstigen Anliegen ist es unser berechtigtes Interesse an der Beantwortung und Dokumentation von Anfragen nach Art. 6 Abs. 1 Buchst. f DSGVO.' ) ); ?></p>
            <p><?php echo esc_html( findewerkstatt_t( 'Die Nachricht wird in einem geschützten Posteingang der Website gespeichert, auf den nur entsprechend berechtigte Administratoren zugreifen können. Zusätzlich wird versucht, eine Benachrichtigung an unsere hinterlegte Kontaktadresse zu versenden. Diese E-Mail enthält Ihren Namen, Ihre E-Mail-Adresse, den Betreff und den vollständigen Nachrichtentext. Der für den Versand eingesetzte Maildienst verarbeitet diese Angaben ebenfalls. Auch wenn der Versand fehlschlägt, bleibt die Anfrage im geschützten Posteingang erhalten.' ) ); ?></p>
            <p><?php echo esc_html( findewerkstatt_t( 'Kontaktanfragen, die älter als 180 Tage sind, werden durch eine regelmäßig ausgeführte Bereinigung aus dem Posteingang entfernt. Bei aktiviertem Papierkorb werden sie zunächst dorthin verschoben; die endgültige Löschung richtet sich nach dessen Einstellungen. Die Ausführung kann sich abhängig vom Betrieb der Website verzögern. E-Mail-Kopien und Sicherungskopien werden durch diese Bereinigung nicht automatisch gelöscht. Für E-Mails richtet sich die Aufbewahrung nach dem Bearbeitungsbedarf, etwaigen gesetzlichen Aufbewahrungspflichten und der Erforderlichkeit zur Durchsetzung oder Abwehr rechtlicher Ansprüche; für Sicherungen nach dem Wiederherstellungszweck und dem Sicherungszyklus.' ) ); ?></p>
            <p><?php echo esc_html( findewerkstatt_t( 'Wenn Sie uns direkt per E-Mail schreiben, verarbeiten wir die von Ihnen übermittelten Inhalte, Ihre Absenderadresse und die technischen Angaben der Nachricht zur Bearbeitung Ihres Anliegens. Diese E-Mails unterliegen der Aufbewahrung im verwendeten Maildienst und werden nicht durch die Bereinigung des Website-Posteingangs gelöscht.' ) ); ?></p>

            <h2 id="werkstattanmeldung"><?php echo esc_html( findewerkstatt_t( '4. Werkstattanmeldung und Veröffentlichung' ) ); ?></h2>
            <p><?php echo esc_html( findewerkstatt_t( 'Bei einer Anmeldung verarbeiten wir den Firmennamen, die E-Mail-Adresse, die Telefonnummer und den angegebenen Ort mit Bundesland. Je nach Ihren Angaben kommen der Name des Ansprechpartners, eine WhatsApp-Nummer, die Website, Straße und Hausnummer, Postleitzahl, Betriebsbeschreibung, Leistungen, Fahrzeugmarken sowie Angaben zum Meisterbetrieb oder Notdienst hinzu. Wir speichern die Bestätigung des Datenschutzhinweises und eine Kennung zur Erkennung doppelter Anmeldungen.' ) ); ?></p>
            <p><?php echo esc_html( findewerkstatt_t( 'Die Angaben werden zunächst zur Prüfung gespeichert. Erst nach einer Freigabe erscheint das Betriebsprofil öffentlich. Der Name des Ansprechpartners bleibt intern. Ihre E-Mail-Adresse verwenden wir zur Kommunikation und veröffentlichen sie nur, wenn Sie die gesonderte Option für eine öffentliche Kontaktadresse auswählen. Angaben wie Firmenname, Betriebsanschrift, Telefonnummer, Website, Beschreibung und Leistungen können nach der Freigabe von Website-Besuchern und Suchmaschinen abgerufen werden.' ) ); ?></p>
            <p><?php echo esc_html( findewerkstatt_t( 'Die Bearbeitung Ihrer gewünschten Anmeldung und die Bereitstellung des Eintrags beruhen auf Art. 6 Abs. 1 Buchst. b DSGVO, soweit sie für das mit Ihnen vereinbarte Eintragsverhältnis erforderlich sind. Handeln Sie als Kontaktperson eines Unternehmens, verarbeiten wir Ihre Kontaktdaten aufgrund unseres berechtigten Interesses an der Abstimmung und Pflege des Eintrags nach Art. 6 Abs. 1 Buchst. f DSGVO. Die freiwillige Veröffentlichung einer personenbezogenen E-Mail-Adresse stützen wir auf Ihre Einwilligung nach Art. 6 Abs. 1 Buchst. a DSGVO. Diese Einwilligung können Sie für die Zukunft über die Kontaktmöglichkeiten in Abschnitt 1 widerrufen; die bisherige Verarbeitung bleibt davon unberührt.' ) ); ?></p>
            <p><?php echo esc_html( findewerkstatt_t( 'Mit * gekennzeichnete Angaben sind für die Bearbeitung der Anmeldung erforderlich. Weitere Angaben und die Freigabe der E-Mail-Adresse zur Veröffentlichung sind freiwillig. Für Anmeldungen und Betriebsprofile gibt es keine einheitliche automatische Löschfrist. Die Speicherdauer richtet sich nach der Prüfung und Pflege des Eintrags sowie der Bearbeitung von Änderungs- oder Entfernungsanfragen. Noch nicht freigegebene Anmeldungen bleiben bis zur Bearbeitung im Prüfbereich gespeichert. Bitte kontaktieren Sie uns, wenn Sie eine Anmeldung zurückziehen oder einen veröffentlichten Eintrag ändern lassen möchten.' ) ); ?></p>

            <h2 id="bestehende-firmendaten"><?php echo esc_html( findewerkstatt_t( '5. Firmendaten aus Google Maps – Herkunft und Löschung' ) ); ?></h2>
            <p><?php echo esc_html( findewerkstatt_t( 'Die übernommenen Betriebsdaten stammen ursprünglich aus öffentlich zugänglichen Unternehmenseinträgen bei Google Maps. Sie wurden im bisherigen Werkstattverzeichnis auf FindeWerkstatt.de erfasst und über den bereitgestellten Export in das aktuelle Verzeichnis übernommen. Es handelt sich insbesondere um Firmennamen, Betriebsanschriften, Orte, Telefonnummern und die dort angegebenen Arten von Dienstleistungen. Diese Angaben zur Herkunft ergänzen die Hinweise nach Art. 14 DSGVO. Soweit Angaben eine natürliche Person betreffen, etwa den Inhaber eines Einzelunternehmens, sind sie personenbezogene Daten.' ) ); ?></p>
            <p><?php echo esc_html( findewerkstatt_t( 'Wir verwenden diese Angaben für die Fortführung, Zuordnung und Pflege des öffentlich zugänglichen Werkstattverzeichnisses. Unser Interesse und das Interesse der Besucher liegen darin, Betriebe anhand ihres Standorts und ihrer Kontaktangaben finden zu können. Rechtsgrundlage für diese Verarbeitung personenbezogener Daten ist Art. 6 Abs. 1 Buchst. f DSGVO. Öffentlich verfügbare Betriebsangaben sind dabei nicht von den Datenschutzrechten ausgenommen.' ) ); ?></p>
            <p><?php echo esc_html( findewerkstatt_t( 'Nach der Veröffentlichung können Website-Besucher und Suchmaschinen die Profilangaben abrufen. Unvollständige oder widersprüchliche Einträge können intern zur Prüfung gespeichert bleiben. Quellkennungen, Zuordnungsnachweise und Prüfvermerke werden intern dokumentiert, um Herkunft, Korrekturen und doppelte Einträge nachvollziehen zu können; diese Nachweise erscheinen nicht im öffentlichen Profil.' ) ); ?></p>
            <p><?php echo esc_html( findewerkstatt_t( 'Für übernommene Profile und ihre internen Herkunftsnachweise besteht keine feste automatische Löschfrist. Maßgeblich ist, ob die Angaben noch für einen aktuellen Verzeichniseintrag, seine Pflege oder den Nachweis einer Korrektur benötigt werden. Sie können uns um Auskunft zur Herkunft eines konkreten Eintrags bitten, unrichtige Angaben melden, die Entfernung anfragen oder nach Abschnitt 9 widersprechen.' ) ); ?></p>
            <p><strong><?php echo esc_html( findewerkstatt_t( 'Löschung auf Anfrage:' ) ); ?></strong> <?php echo esc_html( findewerkstatt_t( 'Als Betriebsinhaber oder hierzu berechtigte Person können Sie die Entfernung Ihres Eintrags und die Löschung der zugehörigen Betriebsdaten aus unserer aktiven Datenbank beantragen. Schreiben Sie an' ) ); ?> <a href="mailto:<?php echo esc_attr( $details['email'] ); ?>"><?php echo esc_html( $details['email'] ); ?></a> <?php echo esc_html( findewerkstatt_t( 'oder verwenden Sie das' ) ); ?> <a href="<?php echo esc_url( findewerkstatt_page_url( 'kontakt' ) ); ?>"><?php echo esc_html( findewerkstatt_t( 'Kontaktformular' ) ); ?></a><?php echo esc_html( findewerkstatt_t( '. Bitte nennen Sie den Betriebsnamen, den Ort und nach Möglichkeit die Adresse der Profilseite. Nach Prüfung Ihrer Berechtigung entfernen wir den Eintrag und löschen die Daten, soweit keine gesetzlichen Aufbewahrungspflichten entgegenstehen. Etwaige gesetzlich aufzubewahrende Angaben werden nur für diesen Zweck weiter gespeichert.' ) ); ?></p>
            <p><?php echo esc_html( findewerkstatt_t( 'Die Löschung betrifft die bei FindeWerkstatt.de gespeicherten Daten; der ursprüngliche Eintrag bei Google Maps wird dadurch nicht geändert. In Sicherungskopien können Daten bis zum Ende des jeweiligen Sicherungszyklus verbleiben. Die gesetzlichen Datenschutzrechte betroffener Personen bestehen unabhängig von einer Berechtigung zur Vertretung des Betriebs.' ) ); ?></p>

            <h2 id="cookies-formularschutz"><?php echo esc_html( findewerkstatt_t( '6. Cookies und Formularschutz' ) ); ?></h2>
            <p><?php echo esc_html( findewerkstatt_t( 'Die Werkstattsuche und die Kontakt- und Anmeldeformulare setzen keine Analyse- oder Werbe-Cookies ein und laden keine externen Schriftarten. Bei der Anmeldung zu Ihrem Werkstattkonto oder zum Verwaltungsbereich verwendet WordPress technisch erforderliche Cookies zur Authentifizierung und zum Schutz der Sitzung. Ohne „Angemeldet bleiben“ läuft die Anmeldung regulär nach zwei Tagen ab; mit dieser Option nach 14 Tagen. Das Abmelden beendet die Anmeldung in diesem Browser. Soweit die Speicherung oder der Zugriff auf Ihrem Gerät für einen ausdrücklich gewünschten Dienst unbedingt erforderlich ist, gilt' ) ); ?> <a href="https://www.gesetze-im-internet.de/ttdsg/__25.html" target="_blank" rel="noopener noreferrer">§ 25 Abs. 2 TDDDG</a><?php echo esc_html( findewerkstatt_t( '. Die Verarbeitung personenbezogener Daten richtet sich zusätzlich nach der DSGVO.' ) ); ?></p>
            <p><?php echo esc_html( findewerkstatt_t( 'Zum Schutz vor automatisierten oder wiederholten Einsendungen verwenden wir Formularprüfungen und zeitlich begrenzte Kennungen auf dem Server. Für die Begrenzung von Einsendungen wird aus Ihrer IP-Adresse mithilfe eines geheimen Schlüssels eine Kennung abgeleitet. Die Begrenzung arbeitet mit einem Zeitfenster von höchstens einer Stunde; die unveränderte IP-Adresse wird in diesem Formularschutz nicht gespeichert. Diese Verarbeitung dient unserem berechtigten Interesse am Schutz der Formulare nach Art. 6 Abs. 1 Buchst. f DSGVO.' ) ); ?></p>
            <p><?php echo esc_html( findewerkstatt_t( 'Auf der Kontoseite wird vor einer Anmeldung eine zufällige Schutzkennung als technisch erforderliches Cookie für 30 Minuten gespeichert. Sie bindet das Registrierungs- und Anmeldeformular an Ihren Browser und schützt vor ungewollten Anmeldungen durch fremde Websites.' ) ); ?></p>
            <p><?php echo esc_html( findewerkstatt_t( 'Bei einem Formularfehler können Ihre eingegebenen Angaben für bis zu 15 Minuten auf dem Server zwischengespeichert werden, damit Sie sie korrigieren können. Diese Zwischeninformation wird beim ersten Abruf entfernt. Eine zusätzliche Kennung für die Formularübermittlung gilt bis zu zwei Stunden. Eine Sperrkennung gegen mehrfache Verarbeitung derselben Einsendung ist für die Bereinigung nach einem Tag vorgesehen; die tatsächliche Bereinigung hängt von der Ausführung der geplanten Aufgaben ab. Diese Fristen ersetzen nicht die in den Abschnitten 3 bis 5 beschriebenen Speicherzeiten der eingegangenen Anfragen und Einträge.' ) ); ?></p>

            <h2 id="externe-dienste"><?php echo esc_html( findewerkstatt_t( '7. Google Maps, WhatsApp und externe Links' ) ); ?></h2>
            <p><?php echo esc_html( findewerkstatt_t( 'Die Werkstattprofile bieten Links zu Google Maps, WhatsApp und gegebenenfalls zur Website des Betriebs. Karten oder Chats werden nicht in die Seite eingebettet. Wenn Sie einen solchen Link öffnen, verlassen Sie unsere Website und der jeweilige Anbieter kann unter anderem Ihre IP-Adresse und technische Zugriffsdaten verarbeiten. Die auf den Profilen verwendeten externen Links unterdrücken die Übermittlung der Herkunftsseite als HTTP-Referer; die Informationen in der Zieladresse werden dennoch an den Anbieter übermittelt.' ) ); ?></p>
            <p><strong><?php echo esc_html( findewerkstatt_t( 'Google Maps:' ) ); ?></strong> <?php echo esc_html( findewerkstatt_t( 'Der Link enthält eine Suchanfrage mit dem Firmennamen und den hinterlegten Adress- und Ortsangaben. Es gelten die' ) ); ?> <a href="https://policies.google.com/privacy?hl=de" target="_blank" rel="noopener noreferrer"><?php echo esc_html( findewerkstatt_t( 'Datenschutzhinweise von Google' ) ); ?><span class="screen-reader-text"> <?php echo esc_html( findewerkstatt_t( '(öffnet einen neuen Tab)' ) ); ?></span></a>.</p>
            <p><strong>WhatsApp:</strong> <?php echo esc_html( findewerkstatt_t( 'Der Link verwendet eine gültige gesonderte WhatsApp-Nummer oder ersatzweise die hinterlegte Telefonnummer des Betriebs. Ob der Betrieb diese Nummer über WhatsApp nutzt, klären Sie direkt mit ihm. Der Link enthält die Zielnummer und einen vorbereiteten Nachrichtentext mit dem Firmennamen. Die Nachricht wird erst gesendet, wenn Sie dies in WhatsApp bestätigen. Es gelten die' ) ); ?> <a href="https://www.whatsapp.com/legal/privacy-policy-eea?lang=de" target="_blank" rel="noopener noreferrer"><?php echo esc_html( findewerkstatt_t( 'Datenschutzhinweise von WhatsApp' ) ); ?><span class="screen-reader-text"> <?php echo esc_html( findewerkstatt_t( '(öffnet einen neuen Tab)' ) ); ?></span></a>.</p>
            <p><?php echo esc_html( findewerkstatt_t( 'Für die weitere Nutzung dieser Dienste und für die Verarbeitung auf verlinkten Firmenwebsites ist der jeweilige Anbieter verantwortlich. Angaben zu Empfängern, Speicherzeiten und einer möglichen Verarbeitung außerhalb der EU oder des EWR finden Sie in dessen Datenschutzhinweisen.' ) ); ?></p>

            <h2 id="datenschutzrechte"><?php echo esc_html( findewerkstatt_t( '8. Ihre Datenschutzrechte' ) ); ?></h2>
            <p><?php echo esc_html( findewerkstatt_t( 'Im Rahmen der gesetzlichen Voraussetzungen können Sie Auskunft über Ihre Daten, deren Berichtigung oder Löschung und eine Einschränkung ihrer Verarbeitung verlangen. Auch Datenübertragbarkeit und ein Widerruf erteilter Einwilligungen können Ihnen zustehen. Ein Widerruf betrifft die künftige Verwendung und ändert nichts an der bis dahin zulässigen Verarbeitung. Kontaktieren Sie uns dazu über Abschnitt 1.' ) ); ?></p>
            <p><?php echo esc_html( findewerkstatt_t( 'Sie können sich außerdem bei einer Datenschutzaufsichtsbehörde beschweren, insbesondere in dem EU-Mitgliedstaat Ihres gewöhnlichen Aufenthalts, Ihres Arbeitsplatzes oder eines vermuteten Verstoßes. Die beschriebenen Anmeldungen werden vor einer Veröffentlichung geprüft; wir treffen keine ausschließlich automatisierten Entscheidungen mit rechtlicher oder vergleichbar erheblicher Wirkung über betroffene Personen.' ) ); ?></p>

            <h2 id="widerspruch"><?php echo esc_html( findewerkstatt_t( '9. Widerspruch nach Art. 21 DSGVO' ) ); ?></h2>
            <p><strong><?php echo esc_html( findewerkstatt_t( 'Gegen Verarbeitungen auf Grundlage berechtigter Interessen können Sie jederzeit aus Gründen widersprechen, die Ihre besondere persönliche Situation betreffen. Das gilt insbesondere auch für personenbezogene Angaben in übernommenen Betriebsprofilen.' ) ); ?></strong></p>
            <p><?php echo esc_html( findewerkstatt_t( 'Nach einem solchen Widerspruch führen wir die betroffene Verarbeitung nur weiter, wenn überwiegende zwingende Gründe nachgewiesen werden können oder sie zur Durchsetzung beziehungsweise Abwehr rechtlicher Ansprüche erforderlich ist. Andernfalls beenden wir sie. Falls Daten für Direktwerbung verwendet werden, können Sie dieser Verwendung jederzeit widersprechen; sie wird dann für diesen Zweck beendet.' ) ); ?></p>
            <p><?php echo esc_html( findewerkstatt_t( 'Senden Sie Ihren Widerspruch an' ) ); ?> <a href="mailto:<?php echo esc_attr( $details['email'] ); ?>"><?php echo esc_html( $details['email'] ); ?></a> <?php echo esc_html( findewerkstatt_t( 'oder über das' ) ); ?> <a href="<?php echo esc_url( findewerkstatt_page_url( 'kontakt' ) ); ?>"><?php echo esc_html( findewerkstatt_t( 'Kontaktformular' ) ); ?></a><?php echo esc_html( findewerkstatt_t( '. Bitte beschreiben Sie, welche Daten oder welches Profil betroffen sind, damit wir Ihr Anliegen zuordnen können.' ) ); ?></p>

            <h2 id="werkstattkonto"><?php echo esc_html( findewerkstatt_t( '10. Werkstattkonto und Paketanfragen' ) ); ?></h2>
            <p><?php echo esc_html( findewerkstatt_t( 'Für ein Werkstattkonto benötigen wir Ihren Namen, Ihre E-Mail-Adresse und ein Passwort. Bei der Kontoerstellung fragen wir kein Paket ab und erstellen keine Paketanfrage. Die Paketauswahl erfolgt beim Eintragen eines Betriebs. Das Passwort wird durch WordPress als Hash gespeichert. Zusätzlich speichern wir die Bestätigung der Nutzungsbedingungen und Datenschutzhinweise mit Zeitpunkt und Version, das aktive Paket, gegebenenfalls Ihre spätere Paketanfrage und deren Prüfstatus sowie die Zuordnung Ihrer Betriebseinträge. Ihr Kontoname und Ihre Konto-E-Mail-Adresse erscheinen nicht automatisch im öffentlichen Betriebsprofil.' ) ); ?></p>
            <p><?php echo esc_html( findewerkstatt_t( 'Bei der Übernahme eines vorhandenen Eintrags speichern wir Ihre Angaben zur Vertretungsberechtigung. Bei einer Änderung speichern wir die beantragten Betriebsangaben und nach Freigabe die bisherigen Werte als internen Prüfvermerk. Diese Anfragen sind nur Ihrem Konto und berechtigten Administratoren zugänglich. Die Prüfung erfolgt manuell; eine passende E-Mail-Adresse allein bewirkt keine Zuordnung. Paketwechsel werden ebenfalls erst nach einer Freigabe wirksam und lösen derzeit keine Zahlung aus.' ) ); ?></p>
            <p><?php echo esc_html( findewerkstatt_t( 'Die Verarbeitung dient der Bereitstellung Ihres Kontos und der Durchführung Ihrer gewünschten Eintrags- und Paketanfragen auf Grundlage von' ) ); ?> <a href="https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:32016R0679" target="_blank" rel="noopener noreferrer">Art. 6 Abs. 1 Buchst. b DSGVO</a><?php echo esc_html( findewerkstatt_t( '. Die Prüfung der Vertretungsberechtigung und die Dokumentation von Änderungen dienen außerdem unserem berechtigten Interesse am Schutz vor unbefugten Änderungen und an nachvollziehbaren Einträgen nach Art. 6 Abs. 1 Buchst. f DSGVO.' ) ); ?></p>
            <p><?php echo esc_html( findewerkstatt_t( 'Kontodaten und offene Anfragen werden für die Dauer des Kontos und ihrer Bearbeitung gespeichert. Für abgeschlossene Prüfvermerke besteht derzeit keine automatische Löschfrist; maßgeblich sind der weitere Pflegebedarf, gesetzliche Aufbewahrungspflichten und die Erforderlichkeit zur Klärung konkreter Ansprüche. Sie können die Schließung Ihres Kontos und die Löschung nicht mehr benötigter Angaben über Abschnitt 1 anfragen. Das öffentliche Betriebsprofil wird dadurch nicht automatisch entfernt; einen Entfernungswunsch können Sie gleichzeitig mitteilen. Für die öffentliche E-Mail-Adresse gelten die gesonderten Hinweise in Abschnitt 4.' ) ); ?></p>
        </div>
    </article>
</main>
<?php get_footer(); ?>
