<?php
/** Authenticated member workspace. Every listing comes from explicit ownership metadata. */
if ( ! defined( 'ABSPATH' ) || ! is_user_logged_in() ) { return; }
if ( ! findewerkstatt_is_workshop_member() ) {
    get_template_part( 'template-parts/member-operator-account' );
    return;
}
$member = wp_get_current_user();
$plans = findewerkstatt_membership_plans();
$plan_id = findewerkstatt_member_plan();
$plan = $plans[ $plan_id ];
$workshops = findewerkstatt_member_owned_workshops();
$counts = array_count_values( wp_list_pluck( $workshops, 'post_status' ) );
$pending = findewerkstatt_member_pending_request();
$has_pending = 'pending' === ( $pending['status'] ?? '' );
$open_requests = findewerkstatt_member_dashboard_open_requests();
$limit = findewerkstatt_member_listing_limit();
$can_add = findewerkstatt_member_can_add_workshop();
$values = $args['values'] ?? array();
$notice_kind = $args['notice_kind'] ?? '';
$notice = $args['notice'] ?? array();
$selected_plan = $args['selected_plan'] ?? 'free';
$section = findewerkstatt_member_dashboard_view( $notice_kind );
$initial = function_exists( 'mb_strtoupper' ) ? mb_strtoupper( mb_substr( $member->display_name, 0, 1 ) ) : strtoupper( substr( $member->display_name, 0, 1 ) );
$registration_url = findewerkstatt_page_url( 'werkstatt-anmelden' );
?>
<div class="fw-dashboard-hero">
    <div class="fw-dashboard-identity">
        <span class="fw-dashboard-avatar" aria-hidden="true"><?php echo esc_html( $initial ); ?></span>
        <div>
            <h1><?php echo esc_html( findewerkstatt_t( 'Mein Werkstattkonto' ) ); ?></h1>
            <div class="fw-dashboard-name-row"><p class="fw-dashboard-name"><?php echo esc_html( $member->display_name ); ?></p><span class="fw-dashboard-plan-badge"><?php echo esc_html( $plan['name'] ); ?></span></div>
            <div class="fw-dashboard-identity-details"><span><?php echo esc_html( $member->user_email ); ?></span><span><?php echo esc_html( findewerkstatt_t( 'Mitglied seit' ) ); ?> <?php echo esc_html( wp_date( 'F Y', strtotime( $member->user_registered . ' UTC' ) ) ); ?></span></div>
        </div>
    </div>
    <div class="fw-dashboard-hero-actions">
        <a class="fw-btn fw-dashboard-add" href="<?php echo esc_url( $can_add ? $registration_url : findewerkstatt_member_dashboard_url( 'paket' ) ); ?>"><?php echo findewerkstatt_member_dashboard_icon( 'plus' ); ?><?php echo $can_add ? findewerkstatt_t( 'Betrieb eintragen' ) : findewerkstatt_t( 'Paket anfragen' ); ?></a>
        <form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><?php findewerkstatt_language_field(); ?><input type="hidden" name="action" value="fw_member_logout"><?php wp_nonce_field( 'fw_member_logout', 'fw_member_nonce' ); ?><button class="fw-btn fw-dashboard-logout" type="submit"><?php echo findewerkstatt_member_dashboard_icon( 'logout' ); ?><?php echo esc_html( findewerkstatt_t( 'Abmelden' ) ); ?></button></form>
    </div>
</div>
<div class="fw-dashboard-layout">
    <aside class="fw-dashboard-sidebar" aria-label="Kontonavigation">
        <nav aria-label="<?php echo esc_attr( findewerkstatt_t( 'Werkstattkonto' ) ); ?>"><p class="fw-dashboard-menu-label"><?php echo esc_html( findewerkstatt_t( 'Mein Betrieb' ) ); ?></p>
            <?php foreach ( array( 'betriebe' => array( 'business', findewerkstatt_t( 'Meine Betriebe' ), count( $workshops ) ), 'uebernehmen' => array( 'claim', findewerkstatt_t( 'Eintrag übernehmen' ), null ), 'anfragen' => array( 'requests', findewerkstatt_t( 'Meine Anfragen' ), $open_requests ), 'paket' => array( 'package', findewerkstatt_t( 'Mein Paket' ), null ) ) as $key => $item ) : $active = $section === $key || ( 'bearbeiten' === $section && 'betriebe' === $key ); ?>
            <a class="fw-dashboard-menu-link<?php echo $active ? ' is-active' : ''; ?>" href="<?php echo esc_url( findewerkstatt_member_dashboard_url( $key ) ); ?>"<?php if ( $active ) { echo ' aria-current="page"'; } ?>><?php echo findewerkstatt_member_dashboard_icon( $item[0] ); ?><span><?php echo esc_html( $item[1] ); ?></span><?php if ( null !== $item[2] ) : ?><span class="fw-dashboard-menu-count"><?php echo (int) $item[2]; ?></span><?php endif; ?></a>
            <?php endforeach; ?>
            <p class="fw-dashboard-menu-label"><?php echo esc_html( findewerkstatt_t( 'Konto und Hilfe' ) ); ?></p>
            <?php foreach ( array( 'einstellungen' => array( 'settings', findewerkstatt_t( 'Kontoeinstellungen' ) ), 'hilfe' => array( 'help', findewerkstatt_t( 'Kontakt und Hilfe' ) ) ) as $key => $item ) : ?>
            <a class="fw-dashboard-menu-link<?php echo $section === $key ? ' is-active' : ''; ?>" href="<?php echo esc_url( findewerkstatt_member_dashboard_url( $key ) ); ?>"<?php if ( $section === $key ) { echo ' aria-current="page"'; } ?>><?php echo findewerkstatt_member_dashboard_icon( $item[0] ); ?><span><?php echo esc_html( $item[1] ); ?></span></a><?php endforeach; ?>
            <?php if ( current_user_can( 'manage_options' ) ) : ?><p class="fw-dashboard-menu-label"><?php echo esc_html( findewerkstatt_t( 'Verwaltung' ) ); ?></p><a class="fw-dashboard-menu-link" href="<?php echo esc_url( admin_url( 'users.php?page=findewerkstatt-memberships' ) ); ?>"><?php echo findewerkstatt_member_dashboard_icon( 'admin' ); ?><span><?php echo esc_html( findewerkstatt_t( 'Mitgliedschaften' ) ); ?></span></a><a class="fw-dashboard-menu-link" href="<?php echo esc_url( admin_url() ); ?>"><?php echo findewerkstatt_member_dashboard_icon( 'settings' ); ?><span><?php echo esc_html( findewerkstatt_t( 'WordPress-Verwaltung' ) ); ?></span></a><?php endif; ?>
        </nav>
        <div class="fw-dashboard-upgrade"><span class="fw-dashboard-upgrade-icon"><?php echo findewerkstatt_member_dashboard_icon( 'package' ); ?></span><h2><?php echo esc_html( findewerkstatt_t( 'Mehrere Standorte?' ) ); ?></h2><p><?php echo esc_html( findewerkstatt_t( 'Vergleichen Sie unsere Pakete und fragen Sie unverbindlich einen Wechsel an.' ) ); ?></p><a href="<?php echo esc_url( findewerkstatt_member_dashboard_url( 'paket' ) ); ?>"><?php echo esc_html( findewerkstatt_t( 'Pakete ansehen' ) ); ?> <?php echo findewerkstatt_member_dashboard_icon( 'arrow' ); ?></a></div>
    </aside>
    <div class="fw-dashboard-content">
        <div class="fw-dashboard-stats" aria-label="<?php echo esc_attr( findewerkstatt_t( 'Ihre Einträge im Überblick' ) ); ?>">
            <?php foreach ( array( array( 'business', findewerkstatt_t( 'Meine Betriebe' ), count( $workshops ), 'orange' ), array( 'check', findewerkstatt_t( 'Veröffentlicht' ), $counts['publish'] ?? 0, 'green' ), array( 'clock', findewerkstatt_t( 'In Prüfung' ), $counts['pending'] ?? 0, 'blue' ), array( 'package', findewerkstatt_t( 'Aktuelles Paket' ), $plan['name'], 'purple' ) ) as $stat ) : ?>
            <div class="fw-dashboard-stat"><span class="fw-dashboard-stat-icon fw-dashboard-stat-<?php echo esc_attr( $stat[3] ); ?>"><?php echo findewerkstatt_member_dashboard_icon( $stat[0] ); ?></span><div><span class="fw-dashboard-stat-label"><?php echo esc_html( $stat[1] ); ?></span><strong><?php echo esc_html( $stat[2] ); ?></strong></div></div><?php endforeach; ?>
        </div>
        <?php if ( $has_pending ) : ?><div class="fw-form-notice fw-form-notice-warning" role="status"><p><?php echo esc_html( findewerkstatt_t( 'Ihre Anfrage für' ) ); ?> <strong><?php echo esc_html( $plans[ $pending['plan'] ]['name'] ); ?></strong> <?php echo esc_html( findewerkstatt_t( 'wird geprüft. Bis zur Freigabe bleibt' ) ); ?> <?php echo esc_html( $plan['name'] ); ?> <?php echo esc_html( findewerkstatt_t( 'aktiv.' ) ); ?></p></div><?php elseif ( 'rejected' === ( $pending['status'] ?? '' ) ) : ?><div class="fw-form-notice fw-form-notice-warning" role="status"><p><?php echo esc_html( findewerkstatt_t( 'Ihre letzte Paketanfrage wurde abgelehnt. Bei Rückfragen erreichen Sie uns unter' ) ); ?> <a href="<?php echo esc_url( findewerkstatt_member_dashboard_url( 'hilfe' ) ); ?>"><?php echo esc_html( findewerkstatt_t( 'Kontakt und Hilfe' ) ); ?></a>.</p></div><?php endif; ?>
        <?php if ( 'betriebe' === $section ) :
            $search = is_string( $_GET['suche'] ?? null ) ? sanitize_text_field( wp_unslash( $_GET['suche'] ) ) : '';
            if ( findewerkstatt_form_length( $search ) > 100 ) { $search = ''; }
            $filter = is_string( $_GET['status'] ?? null ) ? sanitize_key( $_GET['status'] ) : '';
            if ( ! in_array( $filter, array( 'publish', 'pending', 'draft' ), true ) ) { $filter = ''; }
            $shown = array_filter( $workshops, function ( $workshop ) use ( $search, $filter ) {
                $title_matches = '' === $search || ( function_exists( 'mb_stripos' ) ? false !== mb_stripos( $workshop->post_title, $search ) : false !== stripos( $workshop->post_title, $search ) );
                return $title_matches && ( '' === $filter || $workshop->post_status === $filter );
            } ); ?>
        <section class="fw-dashboard-businesses" aria-labelledby="fw-member-workshops-heading">
            <div class="fw-dashboard-section-top"><div><h2 id="fw-member-workshops-heading"><?php echo findewerkstatt_member_dashboard_icon( 'business' ); ?><?php echo esc_html( findewerkstatt_t( 'Meine Betriebseinträge' ) ); ?></h2><p><?php echo esc_html( sprintf( findewerkstatt_t( '%1$d von %2$d Einträgen zugeordnet' ), count( $workshops ), $limit ) ); ?></p></div><a class="fw-btn fw-dashboard-add fw-btn-sm" href="<?php echo esc_url( $can_add ? $registration_url : findewerkstatt_member_dashboard_url( 'paket' ) ); ?>"><?php echo findewerkstatt_member_dashboard_icon( 'plus' ); ?><?php echo $can_add ? findewerkstatt_t( 'Betrieb eintragen' ) : findewerkstatt_t( 'Paket anfragen' ); ?></a></div>
            <?php if ( $workshops ) : ?><form method="get" action="<?php echo esc_url( findewerkstatt_page_url( 'mein-konto' ) ); ?>" class="fw-dashboard-filter"><?php findewerkstatt_language_field(); ?><input type="hidden" name="bereich" value="betriebe"><div><label for="fw-business-search"><?php echo esc_html( findewerkstatt_t( 'Betriebsname' ) ); ?></label><input id="fw-business-search" type="search" name="suche" placeholder="<?php echo esc_attr( findewerkstatt_t( 'In meinen Betrieben suchen' ) ); ?>" maxlength="100" value="<?php echo esc_attr( $search ); ?>"></div><div><label for="fw-business-status"><?php echo esc_html( findewerkstatt_t( 'Status' ) ); ?></label><select id="fw-business-status" name="status"><option value=""><?php echo esc_html( findewerkstatt_t( 'Alle Einträge' ) ); ?></option><?php foreach ( array( 'publish' => findewerkstatt_t( 'Veröffentlicht' ), 'pending' => findewerkstatt_t( 'In Prüfung' ), 'draft' => findewerkstatt_t( 'Entwurf oder pausiert' ) ) as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>" <?php selected( $filter, $key ); ?>><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select></div><button class="fw-btn fw-btn-outline fw-btn-sm" type="submit"><?php echo esc_html( findewerkstatt_t( 'Filtern' ) ); ?></button><?php if ( '' !== $search || '' !== $filter ) : ?><a href="<?php echo esc_url( findewerkstatt_member_dashboard_url( 'betriebe' ) ); ?>"><?php echo esc_html( findewerkstatt_t( 'Zurücksetzen' ) ); ?></a><?php endif; ?></form><?php endif; ?>
            <?php if ( $shown ) : ?><ul class="fw-dashboard-business-list"><?php foreach ( $shown as $workshop ) { findewerkstatt_member_dashboard_workshop_card( $workshop ); } ?></ul>
            <?php elseif ( $workshops ) : ?><div class="fw-dashboard-empty"><span><?php echo findewerkstatt_member_dashboard_icon( 'business' ); ?></span><h3><?php echo esc_html( findewerkstatt_t( 'Keine passenden Einträge' ) ); ?></h3><p><?php echo esc_html( findewerkstatt_t( 'Passen Sie Ihren Suchbegriff oder den Statusfilter an.' ) ); ?></p><a href="<?php echo esc_url( findewerkstatt_member_dashboard_url( 'betriebe' ) ); ?>"><?php echo esc_html( findewerkstatt_t( 'Alle meine Betriebe anzeigen' ) ); ?></a></div>
            <?php else : ?><div class="fw-dashboard-empty"><span><?php echo findewerkstatt_member_dashboard_icon( 'business' ); ?></span><h3><?php echo esc_html( findewerkstatt_t( 'Ihr erster Betriebseintrag' ) ); ?></h3><p><?php echo esc_html( findewerkstatt_t( 'Ihrem Konto ist noch kein Betrieb zugeordnet. Tragen Sie Ihre Werkstatt ein oder beantragen Sie die Zuordnung eines bestehenden Profils.' ) ); ?></p><div><a class="fw-btn fw-dashboard-add" href="<?php echo esc_url( $registration_url ); ?>"><?php echo esc_html( findewerkstatt_t( 'Betrieb eintragen' ) ); ?></a><a class="fw-btn fw-btn-outline" href="<?php echo esc_url( findewerkstatt_member_dashboard_url( 'uebernehmen' ) ); ?>"><?php echo esc_html( findewerkstatt_t( 'Eintrag übernehmen' ) ); ?></a></div></div><?php endif; ?>
            <p class="fw-dashboard-review-note"><?php echo esc_html( findewerkstatt_t( 'Neue Einträge und Änderungen werden vor der Veröffentlichung geprüft. Auch Einträge in Prüfung oder mit pausierter Anzeige zählen zur Paketgrenze. Nach dem Pausieren können Sie einen Eintrag erneut zur Prüfung einreichen.' ) ); ?></p>
            <?php if ( ! $can_add ) : ?><p class="fw-member-quota-note"><?php echo esc_html( findewerkstatt_t( 'Ihre Eintragsgrenze ist erreicht. Für weitere Standorte können Sie ein' ) ); ?> <a href="<?php echo esc_url( findewerkstatt_member_dashboard_url( 'paket' ) ); ?>"><?php echo esc_html( findewerkstatt_t( 'größeres Paket anfragen' ) ); ?></a>.</p><?php endif; ?>
        </section>
        <?php elseif ( in_array( $section, array( 'uebernehmen', 'anfragen', 'bearbeiten' ), true ) ) : ?>
            <?php findewerkstatt_member_render_workshop_tools( array( 'uebernehmen' => 'claim', 'anfragen' => 'requests', 'bearbeiten' => 'edit' )[ $section ], $notice ); ?>
            <?php if ( 'anfragen' === $section ) : ?><section class="fw-box fw-member-workshops"><h2><?php echo esc_html( findewerkstatt_t( 'Paketanfragen' ) ); ?></h2><?php if ( $pending ) : $state_labels = array( 'pending' => findewerkstatt_t( 'In Prüfung' ), 'approved' => findewerkstatt_t( 'Freigegeben' ), 'rejected' => findewerkstatt_t( 'Abgelehnt' ), 'cancelled' => findewerkstatt_t( 'Zurückgezogen' ) ); ?><p><?php echo esc_html( $plans[ $pending['plan'] ]['name'] ); ?> <span class="fw-member-status"><?php echo esc_html( $state_labels[ $pending['status'] ] ); ?></span></p><?php else : ?><p><?php echo esc_html( findewerkstatt_t( 'Sie haben noch keine Paketanfrage gestellt.' ) ); ?></p><?php endif; ?><a class="fw-btn fw-btn-outline fw-btn-sm" href="<?php echo esc_url( findewerkstatt_member_dashboard_url( 'paket' ) ); ?>"><?php echo esc_html( findewerkstatt_t( 'Mein Paket ansehen' ) ); ?></a></section><?php endif; ?>
        <?php elseif ( 'einstellungen' === $section ) : ?>
        <section class="fw-box fw-member-auth-panel" aria-labelledby="fw-member-account-heading"><h2 id="fw-member-account-heading"><?php echo esc_html( findewerkstatt_t( 'Kontoeinstellungen' ) ); ?></h2><p class="fw-member-panel-intro"><?php echo esc_html( findewerkstatt_t( 'Ihr Name und Ihre Konto-E-Mail-Adresse bleiben intern.' ) ); ?></p>
            <form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="fw-form"><?php findewerkstatt_language_field(); ?><input type="hidden" name="action" value="fw_member_account"><?php wp_nonce_field( 'fw_member_account', 'fw_member_nonce' ); ?><div class="fw-form-field"><label for="fw-member-account-name"><?php echo esc_html( findewerkstatt_t( 'Vor- und Nachname *' ) ); ?></label><input id="fw-member-account-name" type="text" name="name" required maxlength="160" autocomplete="name" value="<?php echo esc_attr( 'account' === $notice_kind ? ( $values['name'] ?? $member->display_name ) : $member->display_name ); ?>"></div><p class="fw-member-account-email"><strong><?php echo esc_html( findewerkstatt_t( 'E-Mail-Adresse' ) ); ?></strong><br><?php echo esc_html( $member->user_email ); ?></p><button type="submit" class="fw-btn fw-dashboard-add"><?php echo esc_html( findewerkstatt_t( 'Namen speichern' ) ); ?></button><p class="fw-member-form-link"><a href="<?php echo esc_url( wp_lostpassword_url( findewerkstatt_page_url( 'mein-konto' ) ) ); ?>"><?php echo esc_html( findewerkstatt_t( 'Passwort zurücksetzen' ) ); ?></a></p></form>
            <p class="fw-dashboard-review-note"><?php echo esc_html( findewerkstatt_t( 'Für eine Änderung Ihrer E-Mail-Adresse oder die Schließung Ihres Kontos' ) ); ?> <a href="<?php echo esc_url( findewerkstatt_page_url( 'kontakt' ) ); ?>"><?php echo esc_html( findewerkstatt_t( 'kontaktieren Sie uns' ) ); ?></a>.</p>
        </section>
        <?php elseif ( 'paket' === $section ) : ?>
        <section id="paket-anfragen" class="fw-box fw-member-auth-panel" aria-labelledby="fw-member-plan-request-heading"><h2 id="fw-member-plan-request-heading"><?php echo esc_html( findewerkstatt_t( 'Mein Paket' ) ); ?></h2><div class="fw-dashboard-package-current"><span class="fw-dashboard-plan-badge"><?php echo esc_html( $plan['name'] ); ?></span><p><?php echo esc_html( sprintf( findewerkstatt_t( 'Zugeordnete Betriebseinträge: %1$d / %2$d' ), count( $workshops ), $limit ) ); ?></p></div><p class="fw-member-panel-intro"><?php echo esc_html( findewerkstatt_t( 'Die Preise für Plus und Professional werden später bekannt gegeben. Eine Paketwechsel-Anfrage ist unverbindlich, wird manuell geprüft und löst keine Zahlung aus.' ) ); ?></p>
            <?php if ( $has_pending ) : ?><p><?php echo esc_html( findewerkstatt_t( 'Eine Paketanfrage ist bereits offen. Nach der Prüfung sehen Sie das Ergebnis in Ihrem Konto.' ) ); ?></p><?php else : ?><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="fw-form"><?php findewerkstatt_language_field(); ?><input type="hidden" name="action" value="fw_member_plan_request"><input type="hidden" name="fw_submission_token" value="<?php echo esc_attr( findewerkstatt_form_submission_token( 'member_plan_request' ) ); ?>"><?php wp_nonce_field( 'fw_member_plan_request', 'fw_member_nonce' ); ?><div class="fw-form-field"><label for="fw-member-request-plan"><?php echo esc_html( findewerkstatt_t( 'Gewünschtes Paket' ) ); ?></label><select id="fw-member-request-plan" name="selected_plan" required><option value=""><?php echo esc_html( findewerkstatt_t( 'Bitte auswählen' ) ); ?></option><?php foreach ( $plans as $request_id => $request ) : if ( $request_id === $plan_id ) { continue; } ?><option value="<?php echo esc_attr( $request_id ); ?>" <?php selected( $selected_plan, $request_id ); ?>><?php echo esc_html( sprintf( _n( findewerkstatt_t( '%1$s – bis zu %2$d Betriebseintrag' ), findewerkstatt_t( '%1$s – bis zu %2$d Betriebseinträge' ), $request['listing_limit'], 'findewerkstatt' ), $request['name'], $request['listing_limit'] ) ); ?></option><?php endforeach; ?></select></div><button type="submit" class="fw-btn fw-dashboard-add"><?php echo esc_html( findewerkstatt_t( 'Paketwechsel anfragen' ) ); ?></button></form><?php endif; ?>
            <p class="fw-member-form-link"><a href="<?php echo esc_url( findewerkstatt_page_url( 'pakete' ) ); ?>"><?php echo esc_html( findewerkstatt_t( 'Alle Pakete vergleichen' ) ); ?></a></p>
        </section>
        <?php else : ?><section class="fw-box fw-member-auth-panel"><h2><?php echo esc_html( findewerkstatt_t( 'Kontakt und Hilfe' ) ); ?></h2><p class="fw-member-panel-intro"><?php echo esc_html( findewerkstatt_t( 'Sie haben Fragen zu Ihrem Konto, einer Eintragsanfrage oder Ihrem Paket? Schreiben Sie uns und nennen Sie bei Fragen zu einem Betrieb die betreffende Profiladresse.' ) ); ?></p><a class="fw-btn fw-dashboard-add" href="<?php echo esc_url( findewerkstatt_page_url( 'kontakt' ) ); ?>"><?php echo findewerkstatt_member_dashboard_icon( 'help' ); ?><?php echo esc_html( findewerkstatt_t( 'Kontaktformular öffnen' ) ); ?></a><div class="fw-dashboard-help-links"><a href="<?php echo esc_url( findewerkstatt_page_url( 'datenschutz' ) ); ?>"><?php echo esc_html( findewerkstatt_t( 'Datenschutzerklärung' ) ); ?></a><a href="<?php echo esc_url( findewerkstatt_page_url( 'agb' ) ); ?>"><?php echo esc_html( findewerkstatt_t( 'Nutzungsbedingungen' ) ); ?></a></div></section><?php endif; ?>
    </div>
</div>
