<?php
if ( ! defined( 'ABSPATH' ) ) exit;
function ak_p2_codes() {
    return [
        'P2000'=>'NOx Tuzağı Verimliliği Düşük Banka 1',
        'P2001'=>'NOx Tuzağı Verimliliği Düşük Banka 2',
        'P2002'=>'Partikül Filtre Verimliliği Düşük Banka 1',
        'P2003'=>'Partikül Filtre Verimliliği Düşük Banka 2',
        'P2004'=>'Emme Manifold Ayar Valfi Takılı Açık Banka 1',
        'P2005'=>'Emme Manifold Ayar Valfi Takılı Açık Banka 2',
        'P2006'=>'Emme Manifold Ayar Valfi Takılı Kapalı Banka 1',
        'P2007'=>'Emme Manifold Ayar Valfi Takılı Kapalı Banka 2',
        'P2008'=>'Emme Manifold Ayar Valfi Devre Açık Banka 1',
        'P2009'=>'Emme Manifold Ayar Valfi Devre Düşük Banka 1',
        'P2010'=>'Emme Manifold Ayar Valfi Devre Yüksek Banka 1',
        'P2011'=>'Emme Manifold Ayar Valfi Devre Açık Banka 2',
        'P2012'=>'Emme Manifold Ayar Valfi Devre Düşük Banka 2',
        'P2013'=>'Emme Manifold Ayar Valfi Devre Yüksek Banka 2',
        'P2014'=>'Emme Manifold Ayar Valfi Konum Sensörü Devre Banka 1',
        'P2015'=>'Emme Manifold Ayar Valfi Konum Sensörü Aralık/Performans Banka 1',
        'P2016'=>'Emme Manifold Ayar Valfi Konum Sensörü Düşük Banka 1',
        'P2017'=>'Emme Manifold Ayar Valfi Konum Sensörü Yüksek Banka 1',
        'P2018'=>'Emme Manifold Ayar Valfi Konum Sensörü Aralıklı Banka 1',
        'P2019'=>'Emme Manifold Ayar Valfi Konum Sensörü Devre Banka 2',
        'P2020'=>'Emme Manifold Ayar Valfi Konum Sensörü Aralık/Performans Banka 2',
        'P2021'=>'Emme Manifold Ayar Valfi Konum Sensörü Düşük Banka 2',
        'P2022'=>'Emme Manifold Ayar Valfi Konum Sensörü Yüksek Banka 2',
        'P2023'=>'Emme Manifold Ayar Valfi Konum Sensörü Aralıklı Banka 2',
        'P2024'=>'Buharlaşmalı Yakıt Sıcaklık Sensörü Devre Arızası',
        'P2025'=>'Buharlaşmalı Yakıt Sıcaklık Sensörü Performans',
        'P2026'=>'Buharlaşmalı Yakıt Sıcaklık Sensörü Düşük',
        'P2027'=>'Buharlaşmalı Yakıt Sıcaklık Sensörü Yüksek',
        'P2028'=>'Buharlaşmalı Yakıt Sıcaklık Sensörü Aralıklı',
        'P2029'=>'Yakıt Isıtıcı Devre Arızası',
        'P2030'=>'Yakıt Isıtıcı Devre Performans',
        'P2031'=>'Egzoz Gazı Sıcaklık Sensörü Devre Banka 1 Sensör 2',
        'P2032'=>'Egzoz Gazı Sıcaklık Sensörü Devre Düşük Banka 1 Sensör 2',
        'P2033'=>'Egzoz Gazı Sıcaklık Sensörü Devre Yüksek Banka 1 Sensör 2',
        'P2034'=>'Egzoz Gazı Sıcaklık Sensörü Devre Banka 2 Sensör 2',
        'P2035'=>'Egzoz Gazı Sıcaklık Sensörü Devre Düşük Banka 2 Sensör 2',
        'P2036'=>'Egzoz Gazı Sıcaklık Sensörü Devre Yüksek Banka 2 Sensör 2',
        'P2037'=>'NOx Sensörü Devre Banka 1 Sensör 1',
        'P2038'=>'NOx Sensörü Devre Aralık/Performans Banka 1 Sensör 1',
        'P2039'=>'NOx Sensörü Devre Düşük Banka 1 Sensör 1',
        'P2040'=>'NOx Sensörü Devre Yüksek Banka 1 Sensör 1',
        'P2041'=>'NOx Sensörü Devre Aralıklı Banka 1 Sensör 1',
        'P2042'=>'Reaktif Sıvı Sıcaklık Sensörü Devre Arızası',
        'P2043'=>'Reaktif Sıvı Sıcaklık Sensörü Aralık/Performans',
        'P2044'=>'Reaktif Sıvı Sıcaklık Sensörü Düşük',
        'P2045'=>'Reaktif Sıvı Sıcaklık Sensörü Yüksek',
        'P2046'=>'Reaktif Sıvı Sıcaklık Sensörü Aralıklı',
        'P2047'=>'Reaktif Enjektör Devre Açık Banka 1 Ünite 1',
        'P2048'=>'Reaktif Enjektör Devre Düşük Banka 1 Ünite 1',
        'P2049'=>'Reaktif Enjektör Devre Yüksek Banka 1 Ünite 1',
    ];
}
